{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TypeFamilies #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Groups.OrderAttributesGroupElem where

import Data.List.NonEmpty (NonEmpty)
import Data.Proxy
import Data.Validity
import FIX.Components.Class
import FIX.Fields.MsgType
import FIX.Fields.NoOrderAttributes
import FIX.Fields.OrderAttributeType
import FIX.Fields.OrderAttributeValue
import FIX.Groups.Class
import GHC.Generics (Generic)

-- | GroupSpec
--   { groupName = "NoOrderAttributes"
--   , groupNumberField = "NoOrderAttributes"
--   , groupPieces =
--       [ MessagePieceField "OrderAttributeType" True
--       , MessagePieceField "OrderAttributeValue" False
--       ]
--   }
data OrderAttributesGroupElem = OrderAttributesGroupElem
  { orderAttributesGroupElemOrderAttributeType :: !OrderAttributeType,
    orderAttributesGroupElemOrderAttributeValue :: !(Maybe OrderAttributeValue)
  }
  deriving stock (Show, Eq, Generic)

instance Validity OrderAttributesGroupElem

instance IsComponent OrderAttributesGroupElem where
  toComponentFields ((OrderAttributesGroupElem {..})) =
    mconcat
      [ requiredFieldB orderAttributesGroupElemOrderAttributeType,
        optionalFieldB orderAttributesGroupElemOrderAttributeValue
      ]
  fromComponentFields = do
    orderAttributesGroupElemOrderAttributeType <- requiredFieldP
    orderAttributesGroupElemOrderAttributeValue <- optionalFieldP
    pure (OrderAttributesGroupElem {..})

instance IsGroupElement OrderAttributesGroupElem where
  type GroupNumField OrderAttributesGroupElem = NoOrderAttributes
  mkGroupNum Proxy = NoOrderAttributes
  countGroupNum Proxy = unNoOrderAttributes

makeOrderAttributesGroupElem :: OrderAttributeType -> OrderAttributesGroupElem
makeOrderAttributesGroupElem orderAttributesGroupElemOrderAttributeType =
  let orderAttributesGroupElemOrderAttributeValue = Nothing
   in (OrderAttributesGroupElem {..})
