{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TypeFamilies #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Groups.QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem where

import Data.List.NonEmpty (NonEmpty)
import Data.Proxy
import Data.Validity
import FIX.Components.Class
import FIX.Fields.LegStipulationType
import FIX.Fields.LegStipulationValue
import FIX.Fields.MsgType
import FIX.Fields.NoLegStipulations
import FIX.Groups.Class
import GHC.Generics (Generic)

-- | GroupSpec
--   { groupName = "QuoteRequestRejectRelatedSymLegsLegStipulations"
--   , groupNumberField = "NoLegStipulations"
--   , groupPieces =
--       [ MessagePieceField "LegStipulationType" True
--       , MessagePieceField "LegStipulationValue" False
--       ]
--   }
data QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem = QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem
  { quoteRequestRejectRelatedSymLegsLegStipulationsGroupElemLegStipulationType :: !LegStipulationType,
    quoteRequestRejectRelatedSymLegsLegStipulationsGroupElemLegStipulationValue :: !(Maybe LegStipulationValue)
  }
  deriving stock (Show, Eq, Generic)

instance Validity QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem

instance IsComponent QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem where
  toComponentFields ((QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem {..})) =
    mconcat
      [ requiredFieldB quoteRequestRejectRelatedSymLegsLegStipulationsGroupElemLegStipulationType,
        optionalFieldB quoteRequestRejectRelatedSymLegsLegStipulationsGroupElemLegStipulationValue
      ]
  fromComponentFields = do
    quoteRequestRejectRelatedSymLegsLegStipulationsGroupElemLegStipulationType <- requiredFieldP
    quoteRequestRejectRelatedSymLegsLegStipulationsGroupElemLegStipulationValue <- optionalFieldP
    pure (QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem {..})

instance IsGroupElement QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem where
  type GroupNumField QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem = NoLegStipulations
  mkGroupNum Proxy = NoLegStipulations
  countGroupNum Proxy = unNoLegStipulations

makeQuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem :: LegStipulationType -> QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem
makeQuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem quoteRequestRejectRelatedSymLegsLegStipulationsGroupElemLegStipulationType =
  let quoteRequestRejectRelatedSymLegsLegStipulationsGroupElemLegStipulationValue = Nothing
   in (QuoteRequestRejectRelatedSymLegsLegStipulationsGroupElem {..})
