{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TypeFamilies #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Groups.SecurityAltIDGroupElem where

import Data.List.NonEmpty (NonEmpty)
import Data.Proxy
import Data.Validity
import FIX.Components.Class
import FIX.Fields.MsgType
import FIX.Fields.NoSecurityAltID
import FIX.Fields.SecurityAltID
import FIX.Fields.SecurityAltIDSource
import FIX.Groups.Class
import GHC.Generics (Generic)

-- | GroupSpec
--   { groupName = "NoSecurityAltID"
--   , groupNumberField = "NoSecurityAltID"
--   , groupPieces =
--       [ MessagePieceField "SecurityAltID" True
--       , MessagePieceField "SecurityAltIDSource" False
--       ]
--   }
data SecurityAltIDGroupElem = SecurityAltIDGroupElem
  { securityAltIDGroupElemSecurityAltID :: !SecurityAltID,
    securityAltIDGroupElemSecurityAltIDSource :: !(Maybe SecurityAltIDSource)
  }
  deriving stock (Show, Eq, Generic)

instance Validity SecurityAltIDGroupElem

instance IsComponent SecurityAltIDGroupElem where
  toComponentFields ((SecurityAltIDGroupElem {..})) =
    mconcat
      [ requiredFieldB securityAltIDGroupElemSecurityAltID,
        optionalFieldB securityAltIDGroupElemSecurityAltIDSource
      ]
  fromComponentFields = do
    securityAltIDGroupElemSecurityAltID <- requiredFieldP
    securityAltIDGroupElemSecurityAltIDSource <- optionalFieldP
    pure (SecurityAltIDGroupElem {..})

instance IsGroupElement SecurityAltIDGroupElem where
  type GroupNumField SecurityAltIDGroupElem = NoSecurityAltID
  mkGroupNum Proxy = NoSecurityAltID
  countGroupNum Proxy = unNoSecurityAltID

makeSecurityAltIDGroupElem :: SecurityAltID -> SecurityAltIDGroupElem
makeSecurityAltIDGroupElem securityAltIDGroupElemSecurityAltID =
  let securityAltIDGroupElemSecurityAltIDSource = Nothing
   in (SecurityAltIDGroupElem {..})
