messages:
  # System messages
  - Logon
  - Heartbeat
  - Test
  - Resend
  - Reject
  - Sequence
  - Logout
  # Business messages
  - News
  - QuoteRequest
  - QuoteRequestReject
  - Business
  - Quote
  - QuoteCancel
  - NewOrderSingle
  - Execution
  - SecurityDefinitionRequest
  - SecurityDefinition
