messages:
  # System messages
  - Logon
  - Heartbeat
  # - TestRequest
  # - ResendRequest
  # - Reject
  # - SequenceReset
  - Logout
  # # Business messages
  # - QuoteRequest
  # - News
  # - QuoteRequest
  # - QuoteRequestReject
  # - BusinessMessageReject
  # - Quote
  # - QuoteCancel
  # - NewOrderSingle
  # - ExecutionReport
  # - SecurityDefinitionRequest
  # - SecurityDefinition
