unused-types = true
type-class-roots = false
roots = [
  # General
  "^Main.main$",
  # Generated
  "Paths_",
  "FIX.Components",
  "FIX.Fields",
  "FIX.Groups",
  "FIX.Messages",
]
root-instances = [
]

