name: fix-codegen
version: 0.0.0.0

data-files:
- data/**/*.hs

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers
  - opt-env-conf
  - path
  - path-io
  - process
  - template-haskell
  - text
  - unliftio
  - xml-conduit

executables:
  fix-codegen:
    main: Main.hs
    source-dirs: app
    dependencies:
    - fix-codegen

