name: fix-codegen
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - opt-env-conf
  - path
  - path-io
  - xml-conduit

executables:
  fix-codegen:
    main: Main.hs
    source-dirs: app
    dependencies:
    - fix-codegen

