{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.AllocAccountType where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 798, fieldName = "AllocAccountType", fieldType = FieldTypeInt, fieldValues = [FieldValueSpec {fieldValueEnum = "1", fieldValueDescription = "CARRIED_CUSTOMER_SIDE"},FieldValueSpec {fieldValueEnum = "2", fieldValueDescription = "CARRIED_NON_CUSTOMER_SIDE"},FieldValueSpec {fieldValueEnum = "3", fieldValueDescription = "HOUSE_TRADER"},FieldValueSpec {fieldValueEnum = "4", fieldValueDescription = "FLOOR_TRADER"},FieldValueSpec {fieldValueEnum = "6", fieldValueDescription = "CARRIED_NON_CUSTOMER_SIDE_CROSS_MARGINED"},FieldValueSpec {fieldValueEnum = "7", fieldValueDescription = "HOUSE_TRADER_CROSS_MARGINED"},FieldValueSpec {fieldValueEnum = "8", fieldValueDescription = "JOINT_BACK_OFFICE_ACCOUNT"}]}
data AllocAccountType
  = AllocAccountType_CARRIED_CUSTOMER_SIDE
  | AllocAccountType_CARRIED_NON_CUSTOMER_SIDE
  | AllocAccountType_HOUSE_TRADER
  | AllocAccountType_FLOOR_TRADER
  | AllocAccountType_CARRIED_NON_CUSTOMER_SIDE_CROSS_MARGINED
  | AllocAccountType_HOUSE_TRADER_CROSS_MARGINED
  | AllocAccountType_JOINT_BACK_OFFICE_ACCOUNT
  deriving stock (Show, Eq, Generic)

instance Validity AllocAccountType

instance IsField AllocAccountType where
  fieldTag Proxy = 798
  fieldIsData Proxy = False
  fieldToValue = \case
    AllocAccountType_CARRIED_CUSTOMER_SIDE -> "1"
    AllocAccountType_CARRIED_NON_CUSTOMER_SIDE -> "2"
    AllocAccountType_HOUSE_TRADER -> "3"
    AllocAccountType_FLOOR_TRADER -> "4"
    AllocAccountType_CARRIED_NON_CUSTOMER_SIDE_CROSS_MARGINED -> "6"
    AllocAccountType_HOUSE_TRADER_CROSS_MARGINED -> "7"
    AllocAccountType_JOINT_BACK_OFFICE_ACCOUNT -> "8"
  fieldFromValue = \case
    "1" -> Right AllocAccountType_CARRIED_CUSTOMER_SIDE
    "2" -> Right AllocAccountType_CARRIED_NON_CUSTOMER_SIDE
    "3" -> Right AllocAccountType_HOUSE_TRADER
    "4" -> Right AllocAccountType_FLOOR_TRADER
    "6" -> Right AllocAccountType_CARRIED_NON_CUSTOMER_SIDE_CROSS_MARGINED
    "7" -> Right AllocAccountType_HOUSE_TRADER_CROSS_MARGINED
    "8" -> Right AllocAccountType_JOINT_BACK_OFFICE_ACCOUNT
    v -> Left ("Unknown AllocAccountType: " <> show v)
