{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.AllocNetMoney where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 154, fieldName = "AllocNetMoney", fieldType = FieldTypeAMT, fieldValues = []}
newtype AllocNetMoney = AllocNetMoney {unAllocNetMoney :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity AllocNetMoney

instance IsField AllocNetMoney where
  fieldTag Proxy = 154
  fieldIsData Proxy = False
  fieldToValue = toValue . unAllocNetMoney
  fieldFromValue = fromValue >=> (prettyValidate . AllocNetMoney)
