{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.BookingRefID where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 466, fieldName = "BookingRefID", fieldType = FieldTypeString, fieldValues = []}
newtype BookingRefID = BookingRefID {unBookingRefID :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity BookingRefID

instance IsField BookingRefID where
  fieldTag Proxy = 466
  fieldIsData Proxy = False
  fieldToValue = toValue . unBookingRefID
  fieldFromValue = fromValue >=> (prettyValidate . BookingRefID)
