{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.CardNumber where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 489, fieldName = "CardNumber", fieldType = FieldTypeString, fieldValues = []}
newtype CardNumber = CardNumber {unCardNumber :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity CardNumber

instance IsField CardNumber where
  fieldTag Proxy = 489
  fieldIsData Proxy = False
  fieldToValue = toValue . unCardNumber
  fieldFromValue = fromValue >=> (prettyValidate . CardNumber)
