{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.CardIssNum where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 491, fieldName = "CardIssNum", fieldType = FieldTypeString, fieldValues = []}
newtype CardIssNum = CardIssNum {unCardIssNum :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity CardIssNum

instance IsField CardIssNum where
  fieldTag Proxy = 491
  fieldIsData Proxy = False
  fieldToValue = toValue . unCardIssNum
  fieldFromValue = fromValue >=> (prettyValidate . CardIssNum)
