{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.CashDistribPayRef where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 501, fieldName = "CashDistribPayRef", fieldType = FieldTypeString, fieldValues = []}
newtype CashDistribPayRef = CashDistribPayRef {unCashDistribPayRef :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity CashDistribPayRef

instance IsField CashDistribPayRef where
  fieldTag Proxy = 501
  fieldIsData Proxy = False
  fieldToValue = toValue . unCashDistribPayRef
  fieldFromValue = fromValue >=> (prettyValidate . CashDistribPayRef)
