{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.ClearingFeeIndicator where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 635, fieldName = "ClearingFeeIndicator", fieldType = FieldTypeString, fieldValues = [FieldValueSpec {fieldValueEnum = "B", fieldValueDescription = "CBOE_MEMBER"},FieldValueSpec {fieldValueEnum = "C", fieldValueDescription = "NON_MEMBER_AND_CUSTOMER"},FieldValueSpec {fieldValueEnum = "E", fieldValueDescription = "EQUITY_MEMBER_AND_CLEARING_MEMBER"},FieldValueSpec {fieldValueEnum = "F", fieldValueDescription = "FULL_AND_ASSOCIATE_MEMBER"},FieldValueSpec {fieldValueEnum = "H", fieldValueDescription = "FIRMS106_H_AND106_J"},FieldValueSpec {fieldValueEnum = "I", fieldValueDescription = "GIM"},FieldValueSpec {fieldValueEnum = "L", fieldValueDescription = "LESSEE106_F_EMPLOYEES"},FieldValueSpec {fieldValueEnum = "M", fieldValueDescription = "ALL_OTHER_OWNERSHIP_TYPES"},FieldValueSpec {fieldValueEnum = "1", fieldValueDescription = "FIRST_YEAR_DELEGATE"},FieldValueSpec {fieldValueEnum = "2", fieldValueDescription = "SECOND_YEAR_DELEGATE"},FieldValueSpec {fieldValueEnum = "3", fieldValueDescription = "THIRD_YEAR_DELEGATE"},FieldValueSpec {fieldValueEnum = "4", fieldValueDescription = "FOURTH_YEAR_DELEGATE"},FieldValueSpec {fieldValueEnum = "5", fieldValueDescription = "FIFTH_YEAR_DELEGATE"},FieldValueSpec {fieldValueEnum = "9", fieldValueDescription = "SIXTH_YEAR_DELEGATE"}]}
data ClearingFeeIndicator
  = ClearingFeeIndicator_CBOE_MEMBER
  | ClearingFeeIndicator_NON_MEMBER_AND_CUSTOMER
  | ClearingFeeIndicator_EQUITY_MEMBER_AND_CLEARING_MEMBER
  | ClearingFeeIndicator_FULL_AND_ASSOCIATE_MEMBER
  | ClearingFeeIndicator_FIRMS106_H_AND106_J
  | ClearingFeeIndicator_GIM
  | ClearingFeeIndicator_LESSEE106_F_EMPLOYEES
  | ClearingFeeIndicator_ALL_OTHER_OWNERSHIP_TYPES
  | ClearingFeeIndicator_FIRST_YEAR_DELEGATE
  | ClearingFeeIndicator_SECOND_YEAR_DELEGATE
  | ClearingFeeIndicator_THIRD_YEAR_DELEGATE
  | ClearingFeeIndicator_FOURTH_YEAR_DELEGATE
  | ClearingFeeIndicator_FIFTH_YEAR_DELEGATE
  | ClearingFeeIndicator_SIXTH_YEAR_DELEGATE
  deriving stock (Show, Eq, Generic)

instance Validity ClearingFeeIndicator

instance IsField ClearingFeeIndicator where
  fieldTag Proxy = 635
  fieldIsData Proxy = False
  fieldToValue = \case
    ClearingFeeIndicator_CBOE_MEMBER -> "B"
    ClearingFeeIndicator_NON_MEMBER_AND_CUSTOMER -> "C"
    ClearingFeeIndicator_EQUITY_MEMBER_AND_CLEARING_MEMBER -> "E"
    ClearingFeeIndicator_FULL_AND_ASSOCIATE_MEMBER -> "F"
    ClearingFeeIndicator_FIRMS106_H_AND106_J -> "H"
    ClearingFeeIndicator_GIM -> "I"
    ClearingFeeIndicator_LESSEE106_F_EMPLOYEES -> "L"
    ClearingFeeIndicator_ALL_OTHER_OWNERSHIP_TYPES -> "M"
    ClearingFeeIndicator_FIRST_YEAR_DELEGATE -> "1"
    ClearingFeeIndicator_SECOND_YEAR_DELEGATE -> "2"
    ClearingFeeIndicator_THIRD_YEAR_DELEGATE -> "3"
    ClearingFeeIndicator_FOURTH_YEAR_DELEGATE -> "4"
    ClearingFeeIndicator_FIFTH_YEAR_DELEGATE -> "5"
    ClearingFeeIndicator_SIXTH_YEAR_DELEGATE -> "9"
  fieldFromValue = \case
    "B" -> Right ClearingFeeIndicator_CBOE_MEMBER
    "C" -> Right ClearingFeeIndicator_NON_MEMBER_AND_CUSTOMER
    "E" -> Right ClearingFeeIndicator_EQUITY_MEMBER_AND_CLEARING_MEMBER
    "F" -> Right ClearingFeeIndicator_FULL_AND_ASSOCIATE_MEMBER
    "H" -> Right ClearingFeeIndicator_FIRMS106_H_AND106_J
    "I" -> Right ClearingFeeIndicator_GIM
    "L" -> Right ClearingFeeIndicator_LESSEE106_F_EMPLOYEES
    "M" -> Right ClearingFeeIndicator_ALL_OTHER_OWNERSHIP_TYPES
    "1" -> Right ClearingFeeIndicator_FIRST_YEAR_DELEGATE
    "2" -> Right ClearingFeeIndicator_SECOND_YEAR_DELEGATE
    "3" -> Right ClearingFeeIndicator_THIRD_YEAR_DELEGATE
    "4" -> Right ClearingFeeIndicator_FOURTH_YEAR_DELEGATE
    "5" -> Right ClearingFeeIndicator_FIFTH_YEAR_DELEGATE
    "9" -> Right ClearingFeeIndicator_SIXTH_YEAR_DELEGATE
    v -> Left ("Unknown ClearingFeeIndicator: " <> show v)
