{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.ClientBidID where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 391, fieldName = "ClientBidID", fieldType = FieldTypeString, fieldValues = []}
newtype ClientBidID = ClientBidID {unClientBidID :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity ClientBidID

instance IsField ClientBidID where
  fieldTag Proxy = 391
  fieldIsData Proxy = False
  fieldToValue = toValue . unClientBidID
  fieldFromValue = fromValue >=> (prettyValidate . ClientBidID)
