{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.CollAsgnReason where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 895, fieldName = "CollAsgnReason", fieldType = FieldTypeInt, fieldValues = [FieldValueSpec {fieldValueEnum = "0", fieldValueDescription = "INITIAL"},FieldValueSpec {fieldValueEnum = "1", fieldValueDescription = "SCHEDULED"},FieldValueSpec {fieldValueEnum = "2", fieldValueDescription = "TIME_WARNING"},FieldValueSpec {fieldValueEnum = "3", fieldValueDescription = "MARGIN_DEFICIENCY"},FieldValueSpec {fieldValueEnum = "4", fieldValueDescription = "MARGIN_EXCESS"},FieldValueSpec {fieldValueEnum = "5", fieldValueDescription = "FORWARD_COLLATERAL_DEMAND"},FieldValueSpec {fieldValueEnum = "6", fieldValueDescription = "EVENT_OF_DEFAULT"},FieldValueSpec {fieldValueEnum = "7", fieldValueDescription = "ADVERSE_TAX_EVENT"}]}
data CollAsgnReason
  = CollAsgnReason_INITIAL
  | CollAsgnReason_SCHEDULED
  | CollAsgnReason_TIME_WARNING
  | CollAsgnReason_MARGIN_DEFICIENCY
  | CollAsgnReason_MARGIN_EXCESS
  | CollAsgnReason_FORWARD_COLLATERAL_DEMAND
  | CollAsgnReason_EVENT_OF_DEFAULT
  | CollAsgnReason_ADVERSE_TAX_EVENT
  deriving stock (Show, Eq, Generic)

instance Validity CollAsgnReason

instance IsField CollAsgnReason where
  fieldTag Proxy = 895
  fieldIsData Proxy = False
  fieldToValue = \case
    CollAsgnReason_INITIAL -> "0"
    CollAsgnReason_SCHEDULED -> "1"
    CollAsgnReason_TIME_WARNING -> "2"
    CollAsgnReason_MARGIN_DEFICIENCY -> "3"
    CollAsgnReason_MARGIN_EXCESS -> "4"
    CollAsgnReason_FORWARD_COLLATERAL_DEMAND -> "5"
    CollAsgnReason_EVENT_OF_DEFAULT -> "6"
    CollAsgnReason_ADVERSE_TAX_EVENT -> "7"
  fieldFromValue = \case
    "0" -> Right CollAsgnReason_INITIAL
    "1" -> Right CollAsgnReason_SCHEDULED
    "2" -> Right CollAsgnReason_TIME_WARNING
    "3" -> Right CollAsgnReason_MARGIN_DEFICIENCY
    "4" -> Right CollAsgnReason_MARGIN_EXCESS
    "5" -> Right CollAsgnReason_FORWARD_COLLATERAL_DEMAND
    "6" -> Right CollAsgnReason_EVENT_OF_DEFAULT
    "7" -> Right CollAsgnReason_ADVERSE_TAX_EVENT
    v -> Left ("Unknown CollAsgnReason: " <> show v)
