{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.ConfirmReqID where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 859, fieldName = "ConfirmReqID", fieldType = FieldTypeString, fieldValues = []}
newtype ConfirmReqID = ConfirmReqID {unConfirmReqID :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity ConfirmReqID

instance IsField ConfirmReqID where
  fieldTag Proxy = 859
  fieldIsData Proxy = False
  fieldToValue = toValue . unConfirmReqID
  fieldFromValue = fromValue >=> (prettyValidate . ConfirmReqID)
