{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.ContraBroker where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 375
--   , fieldName = "ContraBroker"
--   , fieldType = FieldTypeString
--   , fieldValues = []
--   }
newtype ContraBroker = ContraBroker {unContraBroker :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity ContraBroker

instance IsField ContraBroker where
  fieldTag Proxy = 375
  fieldIsData Proxy = False
  fieldToValue = toValue . unContraBroker
  fieldFromValue = fromValue >=> (prettyValidate . ContraBroker)
