{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.ContraryInstructionIndicator where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 719, fieldName = "ContraryInstructionIndicator", fieldType = FieldTypeBoolean, fieldValues = []}
newtype ContraryInstructionIndicator = ContraryInstructionIndicator {unContraryInstructionIndicator :: Bool}
  deriving stock (Show, Eq, Generic)

instance Validity ContraryInstructionIndicator

instance IsField ContraryInstructionIndicator where
  fieldTag Proxy = 719
  fieldIsData Proxy = False
  fieldToValue = toValue . unContraryInstructionIndicator
  fieldFromValue = fromValue >=> (prettyValidate . ContraryInstructionIndicator)
