{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.CxlRejResponseTo where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 434, fieldName = "CxlRejResponseTo", fieldType = FieldTypeChar, fieldValues = [FieldValueSpec {fieldValueEnum = "1", fieldValueDescription = "ORDER_CANCEL_REQUEST"},FieldValueSpec {fieldValueEnum = "2", fieldValueDescription = "ORDER_CANCEL"}]}
data CxlRejResponseTo
  = CxlRejResponseTo_ORDER_CANCEL_REQUEST
  | CxlRejResponseTo_ORDER_CANCEL
  deriving stock (Show, Eq, Generic)

instance Validity CxlRejResponseTo

instance IsField CxlRejResponseTo where
  fieldTag Proxy = 434
  fieldIsData Proxy = False
  fieldToValue = \case
    CxlRejResponseTo_ORDER_CANCEL_REQUEST -> "1"
    CxlRejResponseTo_ORDER_CANCEL -> "2"
  fieldFromValue = \case
    "1" -> Right CxlRejResponseTo_ORDER_CANCEL_REQUEST
    "2" -> Right CxlRejResponseTo_ORDER_CANCEL
    v -> Left ("Unknown CxlRejResponseTo: " <> show v)
