{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.DayCumQty where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 425, fieldName = "DayCumQty", fieldType = FieldTypeQTY, fieldValues = []}
newtype DayCumQty = DayCumQty {unDayCumQty :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity DayCumQty

instance IsField DayCumQty where
  fieldTag Proxy = 425
  fieldIsData Proxy = False
  fieldToValue = toValue . unDayCumQty
  fieldFromValue = fromValue >=> (prettyValidate . DayCumQty)
