{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.DayOrderQty where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 424
--   , fieldName = "DayOrderQty"
--   , fieldType = FieldTypeQTY
--   , fieldValues = []
--   }
newtype DayOrderQty = DayOrderQty {unDayOrderQty :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity DayOrderQty

instance IsField DayOrderQty where
  fieldTag Proxy = 424
  fieldIsData Proxy = False
  fieldToValue = toValue . unDayOrderQty
  fieldFromValue = fromValue >=> (prettyValidate . DayOrderQty)
