{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.DefBidSize where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 293, fieldName = "DefBidSize", fieldType = FieldTypeQTY, fieldValues = []}
newtype DefBidSize = DefBidSize {unDefBidSize :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity DefBidSize

instance IsField DefBidSize where
  fieldTag Proxy = 293
  fieldIsData Proxy = False
  fieldToValue = toValue . unDefBidSize
  fieldFromValue = fromValue >=> (prettyValidate . DefBidSize)
