{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.EncodedSubjectLen where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 356, fieldName = "EncodedSubjectLen", fieldType = FieldTypeLength, fieldValues = []}
newtype EncodedSubjectLen = EncodedSubjectLen {unEncodedSubjectLen :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity EncodedSubjectLen

instance IsField EncodedSubjectLen where
  fieldTag Proxy = 356
  fieldIsData Proxy = False
  fieldToValue = toValue . unEncodedSubjectLen
  fieldFromValue = fromValue >=> (prettyValidate . EncodedSubjectLen)
