{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.EndDate where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 917, fieldName = "EndDate", fieldType = FieldTypeLocalMktDate, fieldValues = []}
newtype EndDate = EndDate {unEndDate :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity EndDate

instance IsField EndDate where
  fieldTag Proxy = 917
  fieldIsData Proxy = False
  fieldToValue = toValue . unEndDate
  fieldFromValue = fromValue >=> (prettyValidate . EndDate)
