{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.FixingTime where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 7544
--   , fieldName = "FixingTime"
--   , fieldType = FieldTypeUTCTimestamp
--   , fieldValues = []
--   }
newtype FixingTime = FixingTime {unFixingTime :: UTCTimestamp}
  deriving stock (Show, Eq, Generic)

instance Validity FixingTime

instance IsField FixingTime where
  fieldTag Proxy = 7544
  fieldIsData Proxy = False
  fieldToValue = toValue . unFixingTime
  fieldFromValue = fromValue >=> (prettyValidate . FixingTime)
