{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.ForwardRatePrecision where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 14002
--   , fieldName = "ForwardRatePrecision"
--   , fieldType = FieldTypeInt
--   , fieldValues = []
--   }
newtype ForwardRatePrecision = ForwardRatePrecision {unForwardRatePrecision :: Int}
  deriving stock (Show, Eq, Generic)

instance Validity ForwardRatePrecision

instance IsField ForwardRatePrecision where
  fieldTag Proxy = 14002
  fieldIsData Proxy = False
  fieldToValue = toValue . unForwardRatePrecision
  fieldFromValue = fromValue >=> (prettyValidate . ForwardRatePrecision)
