{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.GapFillFlag where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 123, fieldName = "GapFillFlag", fieldType = FieldTypeBoolean, fieldValues = [FieldValueSpec {fieldValueEnum = "Y", fieldValueDescription = "YES"},FieldValueSpec {fieldValueEnum = "N", fieldValueDescription = "NO"}]}
data GapFillFlag
  = GapFillFlag_YES
  | GapFillFlag_NO
  deriving stock (Show, Eq, Generic)

instance Validity GapFillFlag

instance IsField GapFillFlag where
  fieldTag Proxy = 123
  fieldIsData Proxy = False
  fieldToValue = \case
    GapFillFlag_YES -> "Y"
    GapFillFlag_NO -> "N"
  fieldFromValue = \case
    "Y" -> Right GapFillFlag_YES
    "N" -> Right GapFillFlag_NO
    v -> Left ("Unknown GapFillFlag: " <> show v)
