{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.HaltReasonChar where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 327, fieldName = "HaltReasonChar", fieldType = FieldTypeChar, fieldValues = [FieldValueSpec {fieldValueEnum = "I", fieldValueDescription = "ORDER_IMBALANCE"},FieldValueSpec {fieldValueEnum = "X", fieldValueDescription = "EQUIPMENT_CHANGEOVER"},FieldValueSpec {fieldValueEnum = "P", fieldValueDescription = "NEWS_PENDING"},FieldValueSpec {fieldValueEnum = "D", fieldValueDescription = "NEWS_DISSEMINATION"},FieldValueSpec {fieldValueEnum = "E", fieldValueDescription = "ORDER_INFLUX"},FieldValueSpec {fieldValueEnum = "M", fieldValueDescription = "ADDITIONAL_INFORMATION"}]}
data HaltReasonChar
  = HaltReasonChar_ORDER_IMBALANCE
  | HaltReasonChar_EQUIPMENT_CHANGEOVER
  | HaltReasonChar_NEWS_PENDING
  | HaltReasonChar_NEWS_DISSEMINATION
  | HaltReasonChar_ORDER_INFLUX
  | HaltReasonChar_ADDITIONAL_INFORMATION
  deriving stock (Show, Eq, Generic)

instance Validity HaltReasonChar

instance IsField HaltReasonChar where
  fieldTag Proxy = 327
  fieldIsData Proxy = False
  fieldToValue = \case
    HaltReasonChar_ORDER_IMBALANCE -> "I"
    HaltReasonChar_EQUIPMENT_CHANGEOVER -> "X"
    HaltReasonChar_NEWS_PENDING -> "P"
    HaltReasonChar_NEWS_DISSEMINATION -> "D"
    HaltReasonChar_ORDER_INFLUX -> "E"
    HaltReasonChar_ADDITIONAL_INFORMATION -> "M"
  fieldFromValue = \case
    "I" -> Right HaltReasonChar_ORDER_IMBALANCE
    "X" -> Right HaltReasonChar_EQUIPMENT_CHANGEOVER
    "P" -> Right HaltReasonChar_NEWS_PENDING
    "D" -> Right HaltReasonChar_NEWS_DISSEMINATION
    "E" -> Right HaltReasonChar_ORDER_INFLUX
    "M" -> Right HaltReasonChar_ADDITIONAL_INFORMATION
    v -> Left ("Unknown HaltReasonChar: " <> show v)
