{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.IndividualAllocRejCode where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 776, fieldName = "IndividualAllocRejCode", fieldType = FieldTypeInt, fieldValues = []}
newtype IndividualAllocRejCode = IndividualAllocRejCode {unIndividualAllocRejCode :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity IndividualAllocRejCode

instance IsField IndividualAllocRejCode where
  fieldTag Proxy = 776
  fieldIsData Proxy = False
  fieldToValue = toValue . unIndividualAllocRejCode
  fieldFromValue = fromValue >=> (prettyValidate . IndividualAllocRejCode)
