{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.InstrAttribType where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 871, fieldName = "InstrAttribType", fieldType = FieldTypeInt, fieldValues = [FieldValueSpec {fieldValueEnum = "1", fieldValueDescription = "FLAT"},FieldValueSpec {fieldValueEnum = "2", fieldValueDescription = "ZERO_COUPON"},FieldValueSpec {fieldValueEnum = "3", fieldValueDescription = "INTEREST_BEARING"},FieldValueSpec {fieldValueEnum = "4", fieldValueDescription = "NO_PERIODIC_PAYMENTS"},FieldValueSpec {fieldValueEnum = "5", fieldValueDescription = "VARIABLE_RATE"},FieldValueSpec {fieldValueEnum = "6", fieldValueDescription = "LESS_FEE_FOR_PUT"},FieldValueSpec {fieldValueEnum = "7", fieldValueDescription = "STEPPED_COUPON"},FieldValueSpec {fieldValueEnum = "8", fieldValueDescription = "COUPON_PERIOD"},FieldValueSpec {fieldValueEnum = "9", fieldValueDescription = "WHEN"},FieldValueSpec {fieldValueEnum = "10", fieldValueDescription = "ORIGINAL_ISSUE_DISCOUNT"},FieldValueSpec {fieldValueEnum = "11", fieldValueDescription = "CALLABLE"},FieldValueSpec {fieldValueEnum = "12", fieldValueDescription = "ESCROWED_TO_MATURITY"},FieldValueSpec {fieldValueEnum = "13", fieldValueDescription = "ESCROWED_TO_REDEMPTION_DATE"},FieldValueSpec {fieldValueEnum = "14", fieldValueDescription = "PRE_REFUNDED"},FieldValueSpec {fieldValueEnum = "15", fieldValueDescription = "IN_DEFAULT"},FieldValueSpec {fieldValueEnum = "16", fieldValueDescription = "UNRATED"},FieldValueSpec {fieldValueEnum = "17", fieldValueDescription = "TAXABLE"},FieldValueSpec {fieldValueEnum = "18", fieldValueDescription = "INDEXED"},FieldValueSpec {fieldValueEnum = "19", fieldValueDescription = "SUBJECT_TO_ALTERNATIVE_MINIMUM_TAX"},FieldValueSpec {fieldValueEnum = "20", fieldValueDescription = "ORIGINAL_ISSUE_DISCOUNT_PRICE"},FieldValueSpec {fieldValueEnum = "21", fieldValueDescription = "CALLABLE_BELOW_MATURITY_VALUE"},FieldValueSpec {fieldValueEnum = "22", fieldValueDescription = "CALLABLE_WITHOUT_NOTICE"},FieldValueSpec {fieldValueEnum = "99", fieldValueDescription = "TEXT"}]}
data InstrAttribType
  = InstrAttribType_FLAT
  | InstrAttribType_ZERO_COUPON
  | InstrAttribType_INTEREST_BEARING
  | InstrAttribType_NO_PERIODIC_PAYMENTS
  | InstrAttribType_VARIABLE_RATE
  | InstrAttribType_LESS_FEE_FOR_PUT
  | InstrAttribType_STEPPED_COUPON
  | InstrAttribType_COUPON_PERIOD
  | InstrAttribType_WHEN
  | InstrAttribType_ORIGINAL_ISSUE_DISCOUNT
  | InstrAttribType_CALLABLE
  | InstrAttribType_ESCROWED_TO_MATURITY
  | InstrAttribType_ESCROWED_TO_REDEMPTION_DATE
  | InstrAttribType_PRE_REFUNDED
  | InstrAttribType_IN_DEFAULT
  | InstrAttribType_UNRATED
  | InstrAttribType_TAXABLE
  | InstrAttribType_INDEXED
  | InstrAttribType_SUBJECT_TO_ALTERNATIVE_MINIMUM_TAX
  | InstrAttribType_ORIGINAL_ISSUE_DISCOUNT_PRICE
  | InstrAttribType_CALLABLE_BELOW_MATURITY_VALUE
  | InstrAttribType_CALLABLE_WITHOUT_NOTICE
  | InstrAttribType_TEXT
  deriving stock (Show, Eq, Generic)

instance Validity InstrAttribType

instance IsField InstrAttribType where
  fieldTag Proxy = 871
  fieldIsData Proxy = False
  fieldToValue = \case
    InstrAttribType_FLAT -> "1"
    InstrAttribType_ZERO_COUPON -> "2"
    InstrAttribType_INTEREST_BEARING -> "3"
    InstrAttribType_NO_PERIODIC_PAYMENTS -> "4"
    InstrAttribType_VARIABLE_RATE -> "5"
    InstrAttribType_LESS_FEE_FOR_PUT -> "6"
    InstrAttribType_STEPPED_COUPON -> "7"
    InstrAttribType_COUPON_PERIOD -> "8"
    InstrAttribType_WHEN -> "9"
    InstrAttribType_ORIGINAL_ISSUE_DISCOUNT -> "10"
    InstrAttribType_CALLABLE -> "11"
    InstrAttribType_ESCROWED_TO_MATURITY -> "12"
    InstrAttribType_ESCROWED_TO_REDEMPTION_DATE -> "13"
    InstrAttribType_PRE_REFUNDED -> "14"
    InstrAttribType_IN_DEFAULT -> "15"
    InstrAttribType_UNRATED -> "16"
    InstrAttribType_TAXABLE -> "17"
    InstrAttribType_INDEXED -> "18"
    InstrAttribType_SUBJECT_TO_ALTERNATIVE_MINIMUM_TAX -> "19"
    InstrAttribType_ORIGINAL_ISSUE_DISCOUNT_PRICE -> "20"
    InstrAttribType_CALLABLE_BELOW_MATURITY_VALUE -> "21"
    InstrAttribType_CALLABLE_WITHOUT_NOTICE -> "22"
    InstrAttribType_TEXT -> "99"
  fieldFromValue = \case
    "1" -> Right InstrAttribType_FLAT
    "2" -> Right InstrAttribType_ZERO_COUPON
    "3" -> Right InstrAttribType_INTEREST_BEARING
    "4" -> Right InstrAttribType_NO_PERIODIC_PAYMENTS
    "5" -> Right InstrAttribType_VARIABLE_RATE
    "6" -> Right InstrAttribType_LESS_FEE_FOR_PUT
    "7" -> Right InstrAttribType_STEPPED_COUPON
    "8" -> Right InstrAttribType_COUPON_PERIOD
    "9" -> Right InstrAttribType_WHEN
    "10" -> Right InstrAttribType_ORIGINAL_ISSUE_DISCOUNT
    "11" -> Right InstrAttribType_CALLABLE
    "12" -> Right InstrAttribType_ESCROWED_TO_MATURITY
    "13" -> Right InstrAttribType_ESCROWED_TO_REDEMPTION_DATE
    "14" -> Right InstrAttribType_PRE_REFUNDED
    "15" -> Right InstrAttribType_IN_DEFAULT
    "16" -> Right InstrAttribType_UNRATED
    "17" -> Right InstrAttribType_TAXABLE
    "18" -> Right InstrAttribType_INDEXED
    "19" -> Right InstrAttribType_SUBJECT_TO_ALTERNATIVE_MINIMUM_TAX
    "20" -> Right InstrAttribType_ORIGINAL_ISSUE_DISCOUNT_PRICE
    "21" -> Right InstrAttribType_CALLABLE_BELOW_MATURITY_VALUE
    "22" -> Right InstrAttribType_CALLABLE_WITHOUT_NOTICE
    "99" -> Right InstrAttribType_TEXT
    v -> Left ("Unknown InstrAttribType: " <> show v)
