{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.InstrAttribType where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 871
--   , fieldName = "InstrAttribType"
--   , fieldType = FieldTypeInt
--   , fieldValues =
--       [ FieldValueSpec
--           { fieldValueEnum = "1" , fieldValueDescription = "FLAT" }
--       , FieldValueSpec
--           { fieldValueEnum = "2" , fieldValueDescription = "ZERO_COUPON" }
--       , FieldValueSpec
--           { fieldValueEnum = "3"
--           , fieldValueDescription = "INTEREST_BEARING"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "4"
--           , fieldValueDescription = "NO_PERIODIC_PAYMENTS"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "5" , fieldValueDescription = "VARIABLE_RATE" }
--       , FieldValueSpec
--           { fieldValueEnum = "6"
--           , fieldValueDescription = "LESS_FEE_FOR_PUT"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "7" , fieldValueDescription = "STEPPED_COUPON" }
--       , FieldValueSpec
--           { fieldValueEnum = "8" , fieldValueDescription = "COUPON_PERIOD" }
--       , FieldValueSpec
--           { fieldValueEnum = "9"
--           , fieldValueDescription = "WHEN_AND_IF_ISSUED"
--           }
--       ]
--   }
data InstrAttribType
  = InstrAttribTypeFlat
  | InstrAttribTypeZeroCoupon
  | InstrAttribTypeInterestBearing
  | InstrAttribTypeNoPeriodicPayments
  | InstrAttribTypeVariableRate
  | InstrAttribTypeLessFeeForPut
  | InstrAttribTypeSteppedCoupon
  | InstrAttribTypeCouponPeriod
  | InstrAttribTypeWhenAndIfIssued
  deriving stock (Show, Eq, Generic)

instance Validity InstrAttribType

instance IsField InstrAttribType where
  fieldTag Proxy = 871
  fieldIsData Proxy = False
  fieldToValue = \case
    InstrAttribTypeFlat -> "1"
    InstrAttribTypeZeroCoupon -> "2"
    InstrAttribTypeInterestBearing -> "3"
    InstrAttribTypeNoPeriodicPayments -> "4"
    InstrAttribTypeVariableRate -> "5"
    InstrAttribTypeLessFeeForPut -> "6"
    InstrAttribTypeSteppedCoupon -> "7"
    InstrAttribTypeCouponPeriod -> "8"
    InstrAttribTypeWhenAndIfIssued -> "9"
  fieldFromValue = \case
    "1" -> Right InstrAttribTypeFlat
    "2" -> Right InstrAttribTypeZeroCoupon
    "3" -> Right InstrAttribTypeInterestBearing
    "4" -> Right InstrAttribTypeNoPeriodicPayments
    "5" -> Right InstrAttribTypeVariableRate
    "6" -> Right InstrAttribTypeLessFeeForPut
    "7" -> Right InstrAttribTypeSteppedCoupon
    "8" -> Right InstrAttribTypeCouponPeriod
    "9" -> Right InstrAttribTypeWhenAndIfIssued
    v -> Left ("Unknown InstrAttribType: " <> show v)
