{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.IOIRefID where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 26, fieldName = "IOIRefID", fieldType = FieldTypeString, fieldValues = []}
newtype IOIRefID = IOIRefID {unIOIRefID :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity IOIRefID

instance IsField IOIRefID where
  fieldTag Proxy = 26
  fieldIsData Proxy = False
  fieldToValue = toValue . unIOIRefID
  fieldFromValue = fromValue >=> (prettyValidate . IOIRefID)
