{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.LastForwardPoints2 where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 641
--   , fieldName = "LastForwardPoints2"
--   , fieldType = FieldTypePriceOffset
--   , fieldValues = []
--   }
newtype LastForwardPoints2 = LastForwardPoints2 {unLastForwardPoints2 :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity LastForwardPoints2

instance IsField LastForwardPoints2 where
  fieldTag Proxy = 641
  fieldIsData Proxy = False
  fieldToValue = toValue . unLastForwardPoints2
  fieldFromValue = fromValue >=> (prettyValidate . LastForwardPoints2)
