{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.LegContractSettlMonth where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 955, fieldName = "LegContractSettlMonth", fieldType = FieldTypeMonthYear, fieldValues = []}
newtype LegContractSettlMonth = LegContractSettlMonth {unLegContractSettlMonth :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity LegContractSettlMonth

instance IsField LegContractSettlMonth where
  fieldTag Proxy = 955
  fieldIsData Proxy = False
  fieldToValue = toValue . unLegContractSettlMonth
  fieldFromValue = fromValue >=> (prettyValidate . LegContractSettlMonth)
