{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.LegCurrency where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 556
--   , fieldName = "LegCurrency"
--   , fieldType = FieldTypeCurrency
--   , fieldValues = []
--   }
newtype LegCurrency = LegCurrency {unLegCurrency :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity LegCurrency

instance IsField LegCurrency where
  fieldTag Proxy = 556
  fieldIsData Proxy = False
  fieldToValue = toValue . unLegCurrency
  fieldFromValue = fromValue >=> (prettyValidate . LegCurrency)
