{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.LegOfferExAnteCostPercentage where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 9807
--   , fieldName = "LegOfferExAnteCostPercentage"
--   , fieldType = FieldTypePercentage
--   , fieldValues = []
--   }
newtype LegOfferExAnteCostPercentage = LegOfferExAnteCostPercentage {unLegOfferExAnteCostPercentage :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity LegOfferExAnteCostPercentage

instance IsField LegOfferExAnteCostPercentage where
  fieldTag Proxy = 9807
  fieldIsData Proxy = False
  fieldToValue = toValue . unLegOfferExAnteCostPercentage
  fieldFromValue = fromValue >=> (prettyValidate . LegOfferExAnteCostPercentage)
