{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.LegSecurityAltID where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 605
--   , fieldName = "LegSecurityAltID"
--   , fieldType = FieldTypeString
--   , fieldValues = []
--   }
newtype LegSecurityAltID = LegSecurityAltID {unLegSecurityAltID :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity LegSecurityAltID

instance IsField LegSecurityAltID where
  fieldTag Proxy = 605
  fieldIsData Proxy = False
  fieldToValue = toValue . unLegSecurityAltID
  fieldFromValue = fromValue >=> (prettyValidate . LegSecurityAltID)
