{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.LegStrikePrice where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 612
--   , fieldName = "LegStrikePrice"
--   , fieldType = FieldTypePrice
--   , fieldValues = []
--   }
newtype LegStrikePrice = LegStrikePrice {unLegStrikePrice :: PriceVal}
  deriving stock (Show, Eq, Generic)

instance Validity LegStrikePrice

instance IsField LegStrikePrice where
  fieldTag Proxy = 612
  fieldIsData Proxy = False
  fieldToValue = toValue . unLegStrikePrice
  fieldFromValue = fromValue >=> (prettyValidate . LegStrikePrice)
