{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.LiquidityValue where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 404, fieldName = "LiquidityValue", fieldType = FieldTypeAMT, fieldValues = []}
newtype LiquidityValue = LiquidityValue {unLiquidityValue :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity LiquidityValue

instance IsField LiquidityValue where
  fieldTag Proxy = 404
  fieldIsData Proxy = False
  fieldToValue = toValue . unLiquidityValue
  fieldFromValue = fromValue >=> (prettyValidate . LiquidityValue)
