{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.LiquidityNumSecurities where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 441, fieldName = "LiquidityNumSecurities", fieldType = FieldTypeInt, fieldValues = []}
newtype LiquidityNumSecurities = LiquidityNumSecurities {unLiquidityNumSecurities :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity LiquidityNumSecurities

instance IsField LiquidityNumSecurities where
  fieldTag Proxy = 441
  fieldIsData Proxy = False
  fieldToValue = toValue . unLiquidityNumSecurities
  fieldFromValue = fromValue >=> (prettyValidate . LiquidityNumSecurities)
