{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.LongQty where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 704, fieldName = "LongQty", fieldType = FieldTypeQTY, fieldValues = []}
newtype LongQty = LongQty {unLongQty :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity LongQty

instance IsField LongQty where
  fieldTag Proxy = 704
  fieldIsData Proxy = False
  fieldToValue = toValue . unLongQty
  fieldFromValue = fromValue >=> (prettyValidate . LongQty)
