{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.MailingDtls where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 474, fieldName = "MailingDtls", fieldType = FieldTypeString, fieldValues = []}
newtype MailingDtls = MailingDtls {unMailingDtls :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity MailingDtls

instance IsField MailingDtls where
  fieldTag Proxy = 474
  fieldIsData Proxy = False
  fieldToValue = toValue . unMailingDtls
  fieldFromValue = fromValue >=> (prettyValidate . MailingDtls)
