{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.MDEntryBuyer where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 288, fieldName = "MDEntryBuyer", fieldType = FieldTypeString, fieldValues = []}
newtype MDEntryBuyer = MDEntryBuyer {unMDEntryBuyer :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity MDEntryBuyer

instance IsField MDEntryBuyer where
  fieldTag Proxy = 288
  fieldIsData Proxy = False
  fieldToValue = toValue . unMDEntryBuyer
  fieldFromValue = fromValue >=> (prettyValidate . MDEntryBuyer)
