{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.MDEntryTime where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 273, fieldName = "MDEntryTime", fieldType = FieldTypeUTCTimeOnly, fieldValues = []}
newtype MDEntryTime = MDEntryTime {unMDEntryTime :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity MDEntryTime

instance IsField MDEntryTime where
  fieldTag Proxy = 273
  fieldIsData Proxy = False
  fieldToValue = toValue . unMDEntryTime
  fieldFromValue = fromValue >=> (prettyValidate . MDEntryTime)
