{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.Nested3PartySubIDType where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 954, fieldName = "Nested3PartySubIDType", fieldType = FieldTypeInt, fieldValues = []}
newtype Nested3PartySubIDType = Nested3PartySubIDType {unNested3PartySubIDType :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity Nested3PartySubIDType

instance IsField Nested3PartySubIDType where
  fieldTag Proxy = 954
  fieldIsData Proxy = False
  fieldToValue = toValue . unNested3PartySubIDType
  fieldFromValue = fromValue >=> (prettyValidate . Nested3PartySubIDType)
