{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.NetChgPrevDay where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 451, fieldName = "NetChgPrevDay", fieldType = FieldTypePriceOffset, fieldValues = []}
newtype NetChgPrevDay = NetChgPrevDay {unNetChgPrevDay :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity NetChgPrevDay

instance IsField NetChgPrevDay where
  fieldTag Proxy = 451
  fieldIsData Proxy = False
  fieldToValue = toValue . unNetChgPrevDay
  fieldFromValue = fromValue >=> (prettyValidate . NetChgPrevDay)
