{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.NoCollInquiryQualifier where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 938, fieldName = "NoCollInquiryQualifier", fieldType = FieldTypeNumInGroup, fieldValues = []}
newtype NoCollInquiryQualifier = NoCollInquiryQualifier {unNoCollInquiryQualifier :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity NoCollInquiryQualifier

instance IsField NoCollInquiryQualifier where
  fieldTag Proxy = 938
  fieldIsData Proxy = False
  fieldToValue = toValue . unNoCollInquiryQualifier
  fieldFromValue = fromValue >=> (prettyValidate . NoCollInquiryQualifier)
