{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.NoDlvyInst where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 85, fieldName = "NoDlvyInst", fieldType = FieldTypeNumInGroup, fieldValues = []}
newtype NoDlvyInst = NoDlvyInst {unNoDlvyInst :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity NoDlvyInst

instance IsField NoDlvyInst where
  fieldTag Proxy = 85
  fieldIsData Proxy = False
  fieldToValue = toValue . unNoDlvyInst
  fieldFromValue = fromValue >=> (prettyValidate . NoDlvyInst)
