{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.NoLegs where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 555, fieldName = "NoLegs", fieldType = FieldTypeNumInGroup, fieldValues = []}
newtype NoLegs = NoLegs {unNoLegs :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity NoLegs

instance IsField NoLegs where
  fieldTag Proxy = 555
  fieldIsData Proxy = False
  fieldToValue = toValue . unNoLegs
  fieldFromValue = fromValue >=> (prettyValidate . NoLegs)
