{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.OfferPx where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 133, fieldName = "OfferPx", fieldType = FieldTypePrice, fieldValues = []}
newtype OfferPx = OfferPx {unOfferPx :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity OfferPx

instance IsField OfferPx where
  fieldTag Proxy = 133
  fieldIsData Proxy = False
  fieldToValue = toValue . unOfferPx
  fieldFromValue = fromValue >=> (prettyValidate . OfferPx)
