{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.OfferForwardPoints2 where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 643
--   , fieldName = "OfferForwardPoints2"
--   , fieldType = FieldTypePriceOffset
--   , fieldValues = []
--   }
newtype OfferForwardPoints2 = OfferForwardPoints2 {unOfferForwardPoints2 :: PriceOffset}
  deriving stock (Show, Eq, Generic)

instance Validity OfferForwardPoints2

instance IsField OfferForwardPoints2 where
  fieldTag Proxy = 643
  fieldIsData Proxy = False
  fieldToValue = toValue . unOfferForwardPoints2
  fieldFromValue = fromValue >=> (prettyValidate . OfferForwardPoints2)
