{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.OnBehalfOfSubID where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec {fieldNumber = 116, fieldName = "OnBehalfOfSubID", fieldType = FieldTypeString, fieldValues = []}
newtype OnBehalfOfSubID = OnBehalfOfSubID {unOnBehalfOfSubID :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity OnBehalfOfSubID

instance IsField OnBehalfOfSubID where
  fieldTag Proxy = 116
  fieldIsData Proxy = False
  fieldToValue = toValue . unOnBehalfOfSubID
  fieldFromValue = fromValue >=> (prettyValidate . OnBehalfOfSubID)
