{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.PartySubIDType where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 803
--   , fieldName = "PartySubIDType"
--   , fieldType = FieldTypeInt
--   , fieldValues = []
--   }
newtype PartySubIDType = PartySubIDType {unPartySubIDType :: Int}
  deriving stock (Show, Eq, Generic)

instance Validity PartySubIDType

instance IsField PartySubIDType where
  fieldTag Proxy = 803
  fieldIsData Proxy = False
  fieldToValue = toValue . unPartySubIDType
  fieldFromValue = fromValue >=> (prettyValidate . PartySubIDType)
