{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.PartyRole where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 452
--   , fieldName = "PartyRole"
--   , fieldType = FieldTypeInt
--   , fieldValues =
--       [ FieldValueSpec
--           { fieldValueEnum = "1" , fieldValueDescription = "EXECUTING_FIRM" }
--       , FieldValueSpec
--           { fieldValueEnum = "2"
--           , fieldValueDescription = "BROKER_OF_CREDIT"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "3" , fieldValueDescription = "CLIENT_ID" }
--       , FieldValueSpec
--           { fieldValueEnum = "4" , fieldValueDescription = "CLEARING_FIRM" }
--       , FieldValueSpec
--           { fieldValueEnum = "5" , fieldValueDescription = "INVESTOR_ID" }
--       , FieldValueSpec
--           { fieldValueEnum = "6"
--           , fieldValueDescription = "INTRODUCING_FIRM"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "7" , fieldValueDescription = "ENTERING_FIRM" }
--       , FieldValueSpec
--           { fieldValueEnum = "8" , fieldValueDescription = "LOCATE" }
--       , FieldValueSpec
--           { fieldValueEnum = "9"
--           , fieldValueDescription = "FUND_MANAGER_CLIENT_ID"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "10"
--           , fieldValueDescription = "SETTLEMENT_LOCATION"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "11"
--           , fieldValueDescription = "ORDER_ORIGINATION_TRADER"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "12"
--           , fieldValueDescription = "EXECUTING_TRADER"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "13"
--           , fieldValueDescription = "ORDER_ORIGINATION_FIRM"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "14"
--           , fieldValueDescription = "GIVEUP_CLEARING_FIRM"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "15"
--           , fieldValueDescription = "CORRESPONDANT_CLEARING_FIRM"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "16"
--           , fieldValueDescription = "EXECUTING_SYSTEM"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "17" , fieldValueDescription = "CONTRA_FIRM" }
--       , FieldValueSpec
--           { fieldValueEnum = "18"
--           , fieldValueDescription = "CONTRA_CLEARING_FIRM"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "19"
--           , fieldValueDescription = "SPONSORING_FIRM"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "20"
--           , fieldValueDescription = "UNDERLYING_CONTRA_FIRM"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "21"
--           , fieldValueDescription = "CLEARING_ORGANIZATION"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "22" , fieldValueDescription = "EXCHANGE" }
--       , FieldValueSpec
--           { fieldValueEnum = "24"
--           , fieldValueDescription = "CUSTOMER_ACCOUNT"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "25"
--           , fieldValueDescription = "CORRESPONDENT_CLEARING_ORGANIZATION"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "26"
--           , fieldValueDescription = "CORRESPONDENT_BROKER"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "27" , fieldValueDescription = "BUYER" }
--       , FieldValueSpec
--           { fieldValueEnum = "28" , fieldValueDescription = "CUSTODIAN" }
--       , FieldValueSpec
--           { fieldValueEnum = "29" , fieldValueDescription = "INTERMEDIARY" }
--       , FieldValueSpec
--           { fieldValueEnum = "30" , fieldValueDescription = "AGENT" }
--       , FieldValueSpec
--           { fieldValueEnum = "31" , fieldValueDescription = "SUB_CUSTODIAN" }
--       , FieldValueSpec
--           { fieldValueEnum = "32" , fieldValueDescription = "BENEFICIARY" }
--       , FieldValueSpec
--           { fieldValueEnum = "33"
--           , fieldValueDescription = "INTERESTED_PARTY"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "34"
--           , fieldValueDescription = "REGULATORY_BODY"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "35"
--           , fieldValueDescription = "LIQUIDITY_PROVIDER"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "36"
--           , fieldValueDescription = "ENTERING_TRADER"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "37" , fieldValueDescription = "CONTRA_TRADER" }
--       , FieldValueSpec
--           { fieldValueEnum = "38"
--           , fieldValueDescription = "POSITION_ACCOUNT"
--           }
--       ]
--   }
data PartyRole
  = PartyRoleExecutingFirm
  | PartyRoleBrokerOfCredit
  | PartyRoleClientId
  | PartyRoleClearingFirm
  | PartyRoleInvestorId
  | PartyRoleIntroducingFirm
  | PartyRoleEnteringFirm
  | PartyRoleLocate
  | PartyRoleFundManagerClientId
  | PartyRoleSettlementLocation
  | PartyRoleOrderOriginationTrader
  | PartyRoleExecutingTrader
  | PartyRoleOrderOriginationFirm
  | PartyRoleGiveupClearingFirm
  | PartyRoleCorrespondantClearingFirm
  | PartyRoleExecutingSystem
  | PartyRoleContraFirm
  | PartyRoleContraClearingFirm
  | PartyRoleSponsoringFirm
  | PartyRoleUnderlyingContraFirm
  | PartyRoleClearingOrganization
  | PartyRoleExchange
  | PartyRoleCustomerAccount
  | PartyRoleCorrespondentClearingOrganization
  | PartyRoleCorrespondentBroker
  | PartyRoleBuyer
  | PartyRoleCustodian
  | PartyRoleIntermediary
  | PartyRoleAgent
  | PartyRoleSubCustodian
  | PartyRoleBeneficiary
  | PartyRoleInterestedParty
  | PartyRoleRegulatoryBody
  | PartyRoleLiquidityProvider
  | PartyRoleEnteringTrader
  | PartyRoleContraTrader
  | PartyRolePositionAccount
  deriving stock (Show, Eq, Generic)

instance Validity PartyRole

instance IsField PartyRole where
  fieldTag Proxy = 452
  fieldIsData Proxy = False
  fieldToValue = \case
    PartyRoleExecutingFirm -> "1"
    PartyRoleBrokerOfCredit -> "2"
    PartyRoleClientId -> "3"
    PartyRoleClearingFirm -> "4"
    PartyRoleInvestorId -> "5"
    PartyRoleIntroducingFirm -> "6"
    PartyRoleEnteringFirm -> "7"
    PartyRoleLocate -> "8"
    PartyRoleFundManagerClientId -> "9"
    PartyRoleSettlementLocation -> "10"
    PartyRoleOrderOriginationTrader -> "11"
    PartyRoleExecutingTrader -> "12"
    PartyRoleOrderOriginationFirm -> "13"
    PartyRoleGiveupClearingFirm -> "14"
    PartyRoleCorrespondantClearingFirm -> "15"
    PartyRoleExecutingSystem -> "16"
    PartyRoleContraFirm -> "17"
    PartyRoleContraClearingFirm -> "18"
    PartyRoleSponsoringFirm -> "19"
    PartyRoleUnderlyingContraFirm -> "20"
    PartyRoleClearingOrganization -> "21"
    PartyRoleExchange -> "22"
    PartyRoleCustomerAccount -> "24"
    PartyRoleCorrespondentClearingOrganization -> "25"
    PartyRoleCorrespondentBroker -> "26"
    PartyRoleBuyer -> "27"
    PartyRoleCustodian -> "28"
    PartyRoleIntermediary -> "29"
    PartyRoleAgent -> "30"
    PartyRoleSubCustodian -> "31"
    PartyRoleBeneficiary -> "32"
    PartyRoleInterestedParty -> "33"
    PartyRoleRegulatoryBody -> "34"
    PartyRoleLiquidityProvider -> "35"
    PartyRoleEnteringTrader -> "36"
    PartyRoleContraTrader -> "37"
    PartyRolePositionAccount -> "38"
  fieldFromValue = \case
    "1" -> Right PartyRoleExecutingFirm
    "2" -> Right PartyRoleBrokerOfCredit
    "3" -> Right PartyRoleClientId
    "4" -> Right PartyRoleClearingFirm
    "5" -> Right PartyRoleInvestorId
    "6" -> Right PartyRoleIntroducingFirm
    "7" -> Right PartyRoleEnteringFirm
    "8" -> Right PartyRoleLocate
    "9" -> Right PartyRoleFundManagerClientId
    "10" -> Right PartyRoleSettlementLocation
    "11" -> Right PartyRoleOrderOriginationTrader
    "12" -> Right PartyRoleExecutingTrader
    "13" -> Right PartyRoleOrderOriginationFirm
    "14" -> Right PartyRoleGiveupClearingFirm
    "15" -> Right PartyRoleCorrespondantClearingFirm
    "16" -> Right PartyRoleExecutingSystem
    "17" -> Right PartyRoleContraFirm
    "18" -> Right PartyRoleContraClearingFirm
    "19" -> Right PartyRoleSponsoringFirm
    "20" -> Right PartyRoleUnderlyingContraFirm
    "21" -> Right PartyRoleClearingOrganization
    "22" -> Right PartyRoleExchange
    "24" -> Right PartyRoleCustomerAccount
    "25" -> Right PartyRoleCorrespondentClearingOrganization
    "26" -> Right PartyRoleCorrespondentBroker
    "27" -> Right PartyRoleBuyer
    "28" -> Right PartyRoleCustodian
    "29" -> Right PartyRoleIntermediary
    "30" -> Right PartyRoleAgent
    "31" -> Right PartyRoleSubCustodian
    "32" -> Right PartyRoleBeneficiary
    "33" -> Right PartyRoleInterestedParty
    "34" -> Right PartyRoleRegulatoryBody
    "35" -> Right PartyRoleLiquidityProvider
    "36" -> Right PartyRoleEnteringTrader
    "37" -> Right PartyRoleContraTrader
    "38" -> Right PartyRolePositionAccount
    v -> Left ("Unknown PartyRole: " <> show v)
