{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.PossDupFlag where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec {fieldNumber = 43, fieldName = "PossDupFlag", fieldType = FieldTypeBoolean, fieldValues = [FieldValueSpec {fieldValueEnum = "Y", fieldValueDescription = "YES"},FieldValueSpec {fieldValueEnum = "N", fieldValueDescription = "NO"}]}
data PossDupFlag
  = PossDupFlagYes
  | PossDupFlagNo
  deriving stock (Show, Eq, Generic)

instance Validity PossDupFlag

instance IsField PossDupFlag where
  fieldTag Proxy = 43
  fieldIsData Proxy = False
  fieldToValue = \case
    PossDupFlagYes -> "Y"
    PossDupFlagNo -> "N"
  fieldFromValue = \case
    "Y" -> Right PossDupFlagYes
    "N" -> Right PossDupFlagNo
    v -> Left ("Unknown PossDupFlag: " <> show v)
