{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.QtyType where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 854, fieldName = "QtyType", fieldType = FieldTypeInt, fieldValues = [FieldValueSpec {fieldValueEnum = "0", fieldValueDescription = "UNITS"},FieldValueSpec {fieldValueEnum = "1", fieldValueDescription = "CONTRACTS"}]}
data QtyType
  = QtyType_UNITS
  | QtyType_CONTRACTS
  deriving stock (Show, Eq, Generic)

instance Validity QtyType

instance IsField QtyType where
  fieldTag Proxy = 854
  fieldIsData Proxy = False
  fieldToValue = \case
    QtyType_UNITS -> "0"
    QtyType_CONTRACTS -> "1"
  fieldFromValue = \case
    "0" -> Right QtyType_UNITS
    "1" -> Right QtyType_CONTRACTS
    v -> Left ("Unknown QtyType: " <> show v)
