{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.QuotePriceType where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 692, fieldName = "QuotePriceType", fieldType = FieldTypeInt, fieldValues = [FieldValueSpec {fieldValueEnum = "1", fieldValueDescription = "PERCENT"},FieldValueSpec {fieldValueEnum = "2", fieldValueDescription = "PER_SHARE"},FieldValueSpec {fieldValueEnum = "3", fieldValueDescription = "FIXED_AMOUNT"},FieldValueSpec {fieldValueEnum = "4", fieldValueDescription = "DISCOUNT"},FieldValueSpec {fieldValueEnum = "5", fieldValueDescription = "PREMIUM"},FieldValueSpec {fieldValueEnum = "6", fieldValueDescription = "SPREAD"},FieldValueSpec {fieldValueEnum = "7", fieldValueDescription = "TED_PRICE"},FieldValueSpec {fieldValueEnum = "8", fieldValueDescription = "TED_YIELD"},FieldValueSpec {fieldValueEnum = "9", fieldValueDescription = "YIELD_SPREAD"},FieldValueSpec {fieldValueEnum = "10", fieldValueDescription = "YIELD"}]}
data QuotePriceType
  = QuotePriceType_PERCENT
  | QuotePriceType_PER_SHARE
  | QuotePriceType_FIXED_AMOUNT
  | QuotePriceType_DISCOUNT
  | QuotePriceType_PREMIUM
  | QuotePriceType_SPREAD
  | QuotePriceType_TED_PRICE
  | QuotePriceType_TED_YIELD
  | QuotePriceType_YIELD_SPREAD
  | QuotePriceType_YIELD
  deriving stock (Show, Eq, Generic)

instance Validity QuotePriceType

instance IsField QuotePriceType where
  fieldTag Proxy = 692
  fieldIsData Proxy = False
  fieldToValue = \case
    QuotePriceType_PERCENT -> "1"
    QuotePriceType_PER_SHARE -> "2"
    QuotePriceType_FIXED_AMOUNT -> "3"
    QuotePriceType_DISCOUNT -> "4"
    QuotePriceType_PREMIUM -> "5"
    QuotePriceType_SPREAD -> "6"
    QuotePriceType_TED_PRICE -> "7"
    QuotePriceType_TED_YIELD -> "8"
    QuotePriceType_YIELD_SPREAD -> "9"
    QuotePriceType_YIELD -> "10"
  fieldFromValue = \case
    "1" -> Right QuotePriceType_PERCENT
    "2" -> Right QuotePriceType_PER_SHARE
    "3" -> Right QuotePriceType_FIXED_AMOUNT
    "4" -> Right QuotePriceType_DISCOUNT
    "5" -> Right QuotePriceType_PREMIUM
    "6" -> Right QuotePriceType_SPREAD
    "7" -> Right QuotePriceType_TED_PRICE
    "8" -> Right QuotePriceType_TED_YIELD
    "9" -> Right QuotePriceType_YIELD_SPREAD
    "10" -> Right QuotePriceType_YIELD
    v -> Left ("Unknown QuotePriceType: " <> show v)
