{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.RefCompID where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 930, fieldName = "RefCompID", fieldType = FieldTypeString, fieldValues = []}
newtype RefCompID = RefCompID {unRefCompID :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity RefCompID

instance IsField RefCompID where
  fieldTag Proxy = 930
  fieldIsData Proxy = False
  fieldToValue = toValue . unRefCompID
  fieldFromValue = fromValue >=> (prettyValidate . RefCompID)
