{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.RepurchaseRate where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 227, fieldName = "RepurchaseRate", fieldType = FieldTypePercentage, fieldValues = []}
newtype RepurchaseRate = RepurchaseRate {unRepurchaseRate :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity RepurchaseRate

instance IsField RepurchaseRate where
  fieldTag Proxy = 227
  fieldIsData Proxy = False
  fieldToValue = toValue . unRepurchaseRate
  fieldFromValue = fromValue >=> (prettyValidate . RepurchaseRate)
