{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.SecurityRequestType where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 321, fieldName = "SecurityRequestType", fieldType = FieldTypeInt, fieldValues = [FieldValueSpec {fieldValueEnum = "0", fieldValueDescription = "REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS"},FieldValueSpec {fieldValueEnum = "1", fieldValueDescription = "REQUEST_SECURITY_IDENTITY_FOR_SPECIFICATIONS"},FieldValueSpec {fieldValueEnum = "2", fieldValueDescription = "REQUEST_LIST_SECURITY_TYPES"},FieldValueSpec {fieldValueEnum = "3", fieldValueDescription = "REQUEST_LIST_SECURITIES"}]}
data SecurityRequestType
  = SecurityRequestType_REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS
  | SecurityRequestType_REQUEST_SECURITY_IDENTITY_FOR_SPECIFICATIONS
  | SecurityRequestType_REQUEST_LIST_SECURITY_TYPES
  | SecurityRequestType_REQUEST_LIST_SECURITIES
  deriving stock (Show, Eq, Generic)

instance Validity SecurityRequestType

instance IsField SecurityRequestType where
  fieldTag Proxy = 321
  fieldIsData Proxy = False
  fieldToValue = \case
    SecurityRequestType_REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS -> "0"
    SecurityRequestType_REQUEST_SECURITY_IDENTITY_FOR_SPECIFICATIONS -> "1"
    SecurityRequestType_REQUEST_LIST_SECURITY_TYPES -> "2"
    SecurityRequestType_REQUEST_LIST_SECURITIES -> "3"
  fieldFromValue = \case
    "0" -> Right SecurityRequestType_REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS
    "1" -> Right SecurityRequestType_REQUEST_SECURITY_IDENTITY_FOR_SPECIFICATIONS
    "2" -> Right SecurityRequestType_REQUEST_LIST_SECURITY_TYPES
    "3" -> Right SecurityRequestType_REQUEST_LIST_SECURITIES
    v -> Left ("Unknown SecurityRequestType: " <> show v)
