{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.SecureData where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 91
--   , fieldName = "SecureData"
--   , fieldType = FieldTypeData
--   , fieldValues = []
--   }
newtype SecureData = SecureData {unSecureData :: DataBytes}
  deriving stock (Show, Eq, Generic)

instance Validity SecureData

instance IsField SecureData where
  fieldTag Proxy = 91
  fieldIsData Proxy = True
  fieldToValue = toValue . unSecureData
  fieldFromValue = fromValue >=> (prettyValidate . SecureData)
