{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.SecurityResponseID where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 322
--   , fieldName = "SecurityResponseID"
--   , fieldType = FieldTypeString
--   , fieldValues = []
--   }
newtype SecurityResponseID = SecurityResponseID {unSecurityResponseID :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity SecurityResponseID

instance IsField SecurityResponseID where
  fieldTag Proxy = 322
  fieldIsData Proxy = False
  fieldToValue = toValue . unSecurityResponseID
  fieldFromValue = fromValue >=> (prettyValidate . SecurityResponseID)
