{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.SideValue2 where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 397, fieldName = "SideValue2", fieldType = FieldTypeAMT, fieldValues = []}
newtype SideValue2 = SideValue2 {unSideValue2 :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity SideValue2

instance IsField SideValue2 where
  fieldTag Proxy = 397
  fieldIsData Proxy = False
  fieldToValue = toValue . unSideValue2
  fieldFromValue = fromValue >=> (prettyValidate . SideValue2)
