{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.SolicitedFlag where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 377, fieldName = "SolicitedFlag", fieldType = FieldTypeBoolean, fieldValues = [FieldValueSpec {fieldValueEnum = "Y", fieldValueDescription = "YES"},FieldValueSpec {fieldValueEnum = "N", fieldValueDescription = "NO"}]}
data SolicitedFlag
  = SolicitedFlag_YES
  | SolicitedFlag_NO
  deriving stock (Show, Eq, Generic)

instance Validity SolicitedFlag

instance IsField SolicitedFlag where
  fieldTag Proxy = 377
  fieldIsData Proxy = False
  fieldToValue = \case
    SolicitedFlag_YES -> "Y"
    SolicitedFlag_NO -> "N"
  fieldFromValue = \case
    "Y" -> Right SolicitedFlag_YES
    "N" -> Right SolicitedFlag_NO
    v -> Left ("Unknown SolicitedFlag: " <> show v)
