{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.TargetStrategyParameters where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 848, fieldName = "TargetStrategyParameters", fieldType = FieldTypeString, fieldValues = []}
newtype TargetStrategyParameters = TargetStrategyParameters {unTargetStrategyParameters :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity TargetStrategyParameters

instance IsField TargetStrategyParameters where
  fieldTag Proxy = 848
  fieldIsData Proxy = False
  fieldToValue = toValue . unTargetStrategyParameters
  fieldFromValue = fromValue >=> (prettyValidate . TargetStrategyParameters)
