{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.TimeInForce where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 59
--   , fieldName = "TimeInForce"
--   , fieldType = FieldTypeChar
--   , fieldValues =
--       [ FieldValueSpec
--           { fieldValueEnum = "0" , fieldValueDescription = "DAY" }
--       , FieldValueSpec
--           { fieldValueEnum = "1"
--           , fieldValueDescription = "GOOD_TILL_CANCEL"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "2" , fieldValueDescription = "AT_THE_OPENING" }
--       , FieldValueSpec
--           { fieldValueEnum = "3"
--           , fieldValueDescription = "IMMEDIATE_OR_CANCEL"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "4" , fieldValueDescription = "FILL_OR_KILL" }
--       , FieldValueSpec
--           { fieldValueEnum = "5"
--           , fieldValueDescription = "GOOD_TILL_CROSSING"
--           }
--       , FieldValueSpec
--           { fieldValueEnum = "6" , fieldValueDescription = "GOOD_TILL_DATE" }
--       , FieldValueSpec
--           { fieldValueEnum = "7" , fieldValueDescription = "AT_THE_CLOSE" }
--       ]
--   }
data TimeInForce
  = TimeInForceDay
  | TimeInForceGoodTillCancel
  | TimeInForceAtTheOpening
  | TimeInForceImmediateOrCancel
  | TimeInForceFillOrKill
  | TimeInForceGoodTillCrossing
  | TimeInForceGoodTillDate
  | TimeInForceAtTheClose
  deriving stock (Show, Eq, Generic)

instance Validity TimeInForce

instance IsField TimeInForce where
  fieldTag Proxy = 59
  fieldIsData Proxy = False
  fieldToValue = \case
    TimeInForceDay -> "0"
    TimeInForceGoodTillCancel -> "1"
    TimeInForceAtTheOpening -> "2"
    TimeInForceImmediateOrCancel -> "3"
    TimeInForceFillOrKill -> "4"
    TimeInForceGoodTillCrossing -> "5"
    TimeInForceGoodTillDate -> "6"
    TimeInForceAtTheClose -> "7"
  fieldFromValue = \case
    "0" -> Right TimeInForceDay
    "1" -> Right TimeInForceGoodTillCancel
    "2" -> Right TimeInForceAtTheOpening
    "3" -> Right TimeInForceImmediateOrCancel
    "4" -> Right TimeInForceFillOrKill
    "5" -> Right TimeInForceGoodTillCrossing
    "6" -> Right TimeInForceGoodTillDate
    "7" -> Right TimeInForceAtTheClose
    v -> Left ("Unknown TimeInForce: " <> show v)
