{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.TotalVolumeTraded where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 387, fieldName = "TotalVolumeTraded", fieldType = FieldTypeQTY, fieldValues = []}
newtype TotalVolumeTraded = TotalVolumeTraded {unTotalVolumeTraded :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity TotalVolumeTraded

instance IsField TotalVolumeTraded where
  fieldTag Proxy = 387
  fieldIsData Proxy = False
  fieldToValue = toValue . unTotalVolumeTraded
  fieldFromValue = fromValue >=> (prettyValidate . TotalVolumeTraded)
