{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.TradeLinkID where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 820, fieldName = "TradeLinkID", fieldType = FieldTypeString, fieldValues = []}
newtype TradeLinkID = TradeLinkID {unTradeLinkID :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity TradeLinkID

instance IsField TradeLinkID where
  fieldTag Proxy = 820
  fieldIsData Proxy = False
  fieldToValue = toValue . unTradeLinkID
  fieldFromValue = fromValue >=> (prettyValidate . TradeLinkID)
