{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.TradeInputDevice where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 579, fieldName = "TradeInputDevice", fieldType = FieldTypeString, fieldValues = []}
newtype TradeInputDevice = TradeInputDevice {unTradeInputDevice :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity TradeInputDevice

instance IsField TradeInputDevice where
  fieldTag Proxy = 579
  fieldIsData Proxy = False
  fieldToValue = toValue . unTradeInputDevice
  fieldFromValue = fromValue >=> (prettyValidate . TradeInputDevice)
