{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.TradeAllocIndicator where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 826, fieldName = "TradeAllocIndicator", fieldType = FieldTypeInt, fieldValues = [FieldValueSpec {fieldValueEnum = "0", fieldValueDescription = "ALLOCATION_NOT_REQUIRED"},FieldValueSpec {fieldValueEnum = "1", fieldValueDescription = "ALLOCATION_REQUIRED"},FieldValueSpec {fieldValueEnum = "2", fieldValueDescription = "USE_ALLOCATION_PROVIDED_WITH_THE_TRADE"}]}
data TradeAllocIndicator
  = TradeAllocIndicator_ALLOCATION_NOT_REQUIRED
  | TradeAllocIndicator_ALLOCATION_REQUIRED
  | TradeAllocIndicator_USE_ALLOCATION_PROVIDED_WITH_THE_TRADE
  deriving stock (Show, Eq, Generic)

instance Validity TradeAllocIndicator

instance IsField TradeAllocIndicator where
  fieldTag Proxy = 826
  fieldIsData Proxy = False
  fieldToValue = \case
    TradeAllocIndicator_ALLOCATION_NOT_REQUIRED -> "0"
    TradeAllocIndicator_ALLOCATION_REQUIRED -> "1"
    TradeAllocIndicator_USE_ALLOCATION_PROVIDED_WITH_THE_TRADE -> "2"
  fieldFromValue = \case
    "0" -> Right TradeAllocIndicator_ALLOCATION_NOT_REQUIRED
    "1" -> Right TradeAllocIndicator_ALLOCATION_REQUIRED
    "2" -> Right TradeAllocIndicator_USE_ALLOCATION_PROVIDED_WITH_THE_TRADE
    v -> Left ("Unknown TradeAllocIndicator: " <> show v)
