{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.TrdRegPublicationReason where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 2670
--   , fieldName = "TrdRegPublicationReason"
--   , fieldType = FieldTypeInt
--   , fieldValues = []
--   }
newtype TrdRegPublicationReason = TrdRegPublicationReason {unTrdRegPublicationReason :: Int}
  deriving stock (Show, Eq, Generic)

instance Validity TrdRegPublicationReason

instance IsField TrdRegPublicationReason where
  fieldTag Proxy = 2670
  fieldIsData Proxy = False
  fieldToValue = toValue . unTrdRegPublicationReason
  fieldFromValue = fromValue >=> (prettyValidate . TrdRegPublicationReason)
