{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.UnderlyingCouponRate where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- FieldSpec {fieldNumber = 435, fieldName = "UnderlyingCouponRate", fieldType = FieldTypePercentage, fieldValues = []}
newtype UnderlyingCouponRate = UnderlyingCouponRate {unUnderlyingCouponRate :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity UnderlyingCouponRate

instance IsField UnderlyingCouponRate where
  fieldTag Proxy = 435
  fieldIsData Proxy = False
  fieldToValue = toValue . unUnderlyingCouponRate
  fieldFromValue = fromValue >=> (prettyValidate . UnderlyingCouponRate)
