{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.UnderlyingRedemptionDate where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 247, fieldName = "UnderlyingRedemptionDate", fieldType = FieldTypeLocalMktDate, fieldValues = []}
newtype UnderlyingRedemptionDate = UnderlyingRedemptionDate {unUnderlyingRedemptionDate :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity UnderlyingRedemptionDate

instance IsField UnderlyingRedemptionDate where
  fieldTag Proxy = 247
  fieldIsData Proxy = False
  fieldToValue = toValue . unUnderlyingRedemptionDate
  fieldFromValue = fromValue >=> (prettyValidate . UnderlyingRedemptionDate)
