{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.UnderlyingCurrentValue where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 885
--   , fieldName = "UnderlyingCurrentValue"
--   , fieldType = FieldTypeAMT
--   , fieldValues = []
--   }
newtype UnderlyingCurrentValue = UnderlyingCurrentValue {unUnderlyingCurrentValue :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity UnderlyingCurrentValue

instance IsField UnderlyingCurrentValue where
  fieldTag Proxy = 885
  fieldIsData Proxy = False
  fieldToValue = toValue . unUnderlyingCurrentValue
  fieldFromValue = fromValue >=> (prettyValidate . UnderlyingCurrentValue)
