{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.UnderlyingRepoCollateralSecurityType where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 243
--   , fieldName = "UnderlyingRepoCollateralSecurityType"
--   , fieldType = FieldTypeString
--   , fieldValues = []
--   }
newtype UnderlyingRepoCollateralSecurityType = UnderlyingRepoCollateralSecurityType {unUnderlyingRepoCollateralSecurityType :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity UnderlyingRepoCollateralSecurityType

instance IsField UnderlyingRepoCollateralSecurityType where
  fieldTag Proxy = 243
  fieldIsData Proxy = False
  fieldToValue = toValue . unUnderlyingRepoCollateralSecurityType
  fieldFromValue = fromValue >=> (prettyValidate . UnderlyingRepoCollateralSecurityType)
