{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.USIPrefix2 where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core
import GHC.Generics (Generic)

{-# ANN module ("HLint: ignore" :: String) #-}

-- | FieldSpec
--   { fieldNumber = 7607
--   , fieldName = "USIPrefix2"
--   , fieldType = FieldTypeString
--   , fieldValues = []
--   }
newtype USIPrefix2 = USIPrefix2 {unUSIPrefix2 :: SimpleBytes}
  deriving stock (Show, Eq, Generic)

instance Validity USIPrefix2

instance IsField USIPrefix2 where
  fieldTag Proxy = 7607
  fieldIsData Proxy = False
  fieldToValue = toValue . unUSIPrefix2
  fieldFromValue = fromValue >=> (prettyValidate . USIPrefix2)
