{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.Yield where

import Control.Monad
import Data.ByteString (ByteString)
import Data.Proxy
import Data.Validity
import FIX.Core (IsField (..), IsFieldType (..))
import GHC.Generics (Generic)

{-# ANN module "HLint: ignore" #-}

-- FieldSpec {fieldNumber = 236, fieldName = "Yield", fieldType = FieldTypePercentage, fieldValues = []}
newtype Yield = Yield {unYield :: ByteString}
  deriving stock (Show, Eq, Generic)

instance Validity Yield

instance IsField Yield where
  fieldTag Proxy = 236
  fieldIsData Proxy = False
  fieldToValue = toValue . unYield
  fieldFromValue = fromValue >=> (prettyValidate . Yield)
