{-# OPTIONS_GHC -Wno-orphans #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Fields.Gen where

import Data.GenValidity
import Data.GenValidity.ByteString ()
import FIX.Fields

instance GenValid Account

instance GenValid AdvId

instance GenValid AdvRefID

instance GenValid AdvSide

instance GenValid AdvTransType

instance GenValid AvgPx

instance GenValid BeginSeqNo

instance GenValid BeginString

instance GenValid BodyLength

instance GenValid CheckSum

instance GenValid ClOrdID

instance GenValid Commission

instance GenValid CommType

instance GenValid CumQty

instance GenValid Currency

instance GenValid EndSeqNo

instance GenValid ExecID

instance GenValid ExecInst

instance GenValid ExecRefID

instance GenValid HandlInst

instance GenValid SecurityIDSource

instance GenValid IOIID

instance GenValid IOIQltyInd

instance GenValid IOIRefID

instance GenValid IOIQty

instance GenValid IOITransType

instance GenValid LastCapacity

instance GenValid LastMkt

instance GenValid LastPx

instance GenValid LastQty

instance GenValid NoLinesOfText

instance GenValid MsgSeqNum

instance GenValid MsgType

instance GenValid NewSeqNo

instance GenValid OrderID

instance GenValid OrderQty

instance GenValid OrdStatus

instance GenValid OrdType

instance GenValid OrigClOrdID

instance GenValid OrigTime

instance GenValid PossDupFlag

instance GenValid Price

instance GenValid RefSeqNum

instance GenValid SecurityID

instance GenValid SenderCompID

instance GenValid SenderSubID

instance GenValid SendingTime

instance GenValid Quantity

instance GenValid Side

instance GenValid Symbol

instance GenValid TargetCompID

instance GenValid TargetSubID

instance GenValid Text

instance GenValid TimeInForce

instance GenValid TransactTime

instance GenValid Urgency

instance GenValid ValidUntilTime

instance GenValid SettlType

instance GenValid SettlDate

instance GenValid SymbolSfx

instance GenValid ListID

instance GenValid ListSeqNo

instance GenValid TotNoOrders

instance GenValid ListExecInst

instance GenValid AllocID

instance GenValid AllocTransType

instance GenValid RefAllocID

instance GenValid NoOrders

instance GenValid AvgPxPrecision

instance GenValid TradeDate

instance GenValid PositionEffect

instance GenValid NoAllocs

instance GenValid AllocAccount

instance GenValid AllocQty

instance GenValid ProcessCode

instance GenValid NoRpts

instance GenValid RptSeq

instance GenValid CxlQty

instance GenValid NoDlvyInst

instance GenValid AllocStatus

instance GenValid AllocRejCode

instance GenValid Signature

instance GenValid SecureDataLen

instance GenValid SecureData

instance GenValid SignatureLength

instance GenValid EmailType

instance GenValid RawDataLength

instance GenValid RawData

instance GenValid PossResend

instance GenValid EncryptMethod

instance GenValid StopPx

instance GenValid ExDestination

instance GenValid CxlRejReason

instance GenValid OrdRejReason

instance GenValid IOIQualifier

instance GenValid Issuer

instance GenValid SecurityDesc

instance GenValid HeartBtInt

instance GenValid MinQty

instance GenValid MaxFloor

instance GenValid TestReqID

instance GenValid ReportToExch

instance GenValid LocateReqd

instance GenValid OnBehalfOfCompID

instance GenValid OnBehalfOfSubID

instance GenValid QuoteID

instance GenValid NetMoney

instance GenValid SettlCurrAmt

instance GenValid SettlCurrency

instance GenValid ForexReq

instance GenValid OrigSendingTime

instance GenValid GapFillFlag

instance GenValid NoExecs

instance GenValid ExpireTime

instance GenValid DKReason

instance GenValid DeliverToCompID

instance GenValid DeliverToSubID

instance GenValid IOINaturalFlag

instance GenValid QuoteReqID

instance GenValid BidPx

instance GenValid OfferPx

instance GenValid BidSize

instance GenValid OfferSize

instance GenValid NoMiscFees

instance GenValid MiscFeeAmt

instance GenValid MiscFeeCurr

instance GenValid MiscFeeType

instance GenValid PrevClosePx

instance GenValid ResetSeqNumFlag

instance GenValid SenderLocationID

instance GenValid TargetLocationID

instance GenValid OnBehalfOfLocationID

instance GenValid DeliverToLocationID

instance GenValid NoRelatedSym

instance GenValid Subject

instance GenValid Headline

instance GenValid URLLink

instance GenValid ExecType

instance GenValid LeavesQty

instance GenValid CashOrderQty

instance GenValid AllocAvgPx

instance GenValid AllocNetMoney

instance GenValid SettlCurrFxRate

instance GenValid SettlCurrFxRateCalc

instance GenValid NumDaysInterest

instance GenValid AccruedInterestRate

instance GenValid AccruedInterestAmt

instance GenValid SettlInstMode

instance GenValid AllocText

instance GenValid SettlInstID

instance GenValid SettlInstTransType

instance GenValid EmailThreadID

instance GenValid SettlInstSource

instance GenValid SecurityType

instance GenValid EffectiveTime

instance GenValid StandInstDbType

instance GenValid StandInstDbName

instance GenValid StandInstDbID

instance GenValid SettlDeliveryType

instance GenValid BidSpotRate

instance GenValid BidForwardPoints

instance GenValid OfferSpotRate

instance GenValid OfferForwardPoints

instance GenValid OrderQty2

instance GenValid SettlDate2

instance GenValid LastSpotRate

instance GenValid LastForwardPoints

instance GenValid AllocLinkID

instance GenValid AllocLinkType

instance GenValid SecondaryOrderID

instance GenValid NoIOIQualifiers

instance GenValid MaturityMonthYear

instance GenValid PutOrCall

instance GenValid StrikePrice

instance GenValid CoveredOrUncovered

instance GenValid OptAttribute

instance GenValid SecurityExchange

instance GenValid NotifyBrokerOfCredit

instance GenValid AllocHandlInst

instance GenValid MaxShow

instance GenValid PegOffsetValue

instance GenValid XmlDataLen

instance GenValid XmlData

instance GenValid SettlInstRefID

instance GenValid NoRoutingIDs

instance GenValid RoutingType

instance GenValid RoutingID

instance GenValid Spread

instance GenValid BenchmarkCurveCurrency

instance GenValid BenchmarkCurveName

instance GenValid BenchmarkCurvePoint

instance GenValid CouponRate

instance GenValid CouponPaymentDate

instance GenValid IssueDate

instance GenValid RepurchaseTerm

instance GenValid RepurchaseRate

instance GenValid Factor

instance GenValid TradeOriginationDate

instance GenValid ExDate

instance GenValid ContractMultiplier

instance GenValid NoStipulations

instance GenValid StipulationType

instance GenValid StipulationValue

instance GenValid YieldType

instance GenValid Yield

instance GenValid TotalTakedown

instance GenValid Concession

instance GenValid RepoCollateralSecurityType

instance GenValid RedemptionDate

instance GenValid UnderlyingCouponPaymentDate

instance GenValid UnderlyingIssueDate

instance GenValid UnderlyingRepoCollateralSecurityType

instance GenValid UnderlyingRepurchaseTerm

instance GenValid UnderlyingRepurchaseRate

instance GenValid UnderlyingFactor

instance GenValid UnderlyingRedemptionDate

instance GenValid LegCouponPaymentDate

instance GenValid LegIssueDate

instance GenValid LegRepoCollateralSecurityType

instance GenValid LegRepurchaseTerm

instance GenValid LegRepurchaseRate

instance GenValid LegFactor

instance GenValid LegRedemptionDate

instance GenValid CreditRating

instance GenValid UnderlyingCreditRating

instance GenValid LegCreditRating

instance GenValid TradedFlatSwitch

instance GenValid BasisFeatureDate

instance GenValid BasisFeaturePrice

instance GenValid MDReqID

instance GenValid SubscriptionRequestType

instance GenValid MarketDepth

instance GenValid MDUpdateType

instance GenValid AggregatedBook

instance GenValid NoMDEntryTypes

instance GenValid NoMDEntries

instance GenValid MDEntryType

instance GenValid MDEntryPx

instance GenValid MDEntrySize

instance GenValid MDEntryDate

instance GenValid MDEntryTime

instance GenValid TickDirection

instance GenValid MDMkt

instance GenValid QuoteCondition

instance GenValid TradeCondition

instance GenValid MDEntryID

instance GenValid MDUpdateAction

instance GenValid MDEntryRefID

instance GenValid MDReqRejReason

instance GenValid MDEntryOriginator

instance GenValid LocationID

instance GenValid DeskID

instance GenValid DeleteReason

instance GenValid OpenCloseSettlFlag

instance GenValid SellerDays

instance GenValid MDEntryBuyer

instance GenValid MDEntrySeller

instance GenValid MDEntryPositionNo

instance GenValid FinancialStatus

instance GenValid CorporateAction

instance GenValid DefBidSize

instance GenValid DefOfferSize

instance GenValid NoQuoteEntries

instance GenValid NoQuoteSets

instance GenValid QuoteStatus

instance GenValid QuoteCancelType

instance GenValid QuoteEntryID

instance GenValid QuoteRejectReason

instance GenValid QuoteResponseLevel

instance GenValid QuoteSetID

instance GenValid QuoteRequestType

instance GenValid TotNoQuoteEntries

instance GenValid UnderlyingSecurityIDSource

instance GenValid UnderlyingIssuer

instance GenValid UnderlyingSecurityDesc

instance GenValid UnderlyingSecurityExchange

instance GenValid UnderlyingSecurityID

instance GenValid UnderlyingSecurityType

instance GenValid UnderlyingSymbol

instance GenValid UnderlyingSymbolSfx

instance GenValid UnderlyingMaturityMonthYear

instance GenValid UnderlyingPutOrCall

instance GenValid UnderlyingStrikePrice

instance GenValid UnderlyingOptAttribute

instance GenValid UnderlyingCurrency

instance GenValid SecurityReqID

instance GenValid SecurityRequestType

instance GenValid SecurityResponseID

instance GenValid SecurityResponseType

instance GenValid SecurityStatusReqID

instance GenValid UnsolicitedIndicator

instance GenValid SecurityTradingStatus

instance GenValid HaltReasonChar

instance GenValid InViewOfCommon

instance GenValid DueToRelated

instance GenValid BuyVolume

instance GenValid SellVolume

instance GenValid HighPx

instance GenValid LowPx

instance GenValid Adjustment

instance GenValid TradSesReqID

instance GenValid TradingSessionID

instance GenValid ContraTrader

instance GenValid TradSesMethod

instance GenValid TradSesMode

instance GenValid TradSesStatus

instance GenValid TradSesStartTime

instance GenValid TradSesOpenTime

instance GenValid TradSesPreCloseTime

instance GenValid TradSesCloseTime

instance GenValid TradSesEndTime

instance GenValid NumberOfOrders

instance GenValid MessageEncoding

instance GenValid EncodedIssuerLen

instance GenValid EncodedIssuer

instance GenValid EncodedSecurityDescLen

instance GenValid EncodedSecurityDesc

instance GenValid EncodedListExecInstLen

instance GenValid EncodedListExecInst

instance GenValid EncodedTextLen

instance GenValid EncodedText

instance GenValid EncodedSubjectLen

instance GenValid EncodedSubject

instance GenValid EncodedHeadlineLen

instance GenValid EncodedHeadline

instance GenValid EncodedAllocTextLen

instance GenValid EncodedAllocText

instance GenValid EncodedUnderlyingIssuerLen

instance GenValid EncodedUnderlyingIssuer

instance GenValid EncodedUnderlyingSecurityDescLen

instance GenValid EncodedUnderlyingSecurityDesc

instance GenValid AllocPrice

instance GenValid QuoteSetValidUntilTime

instance GenValid QuoteEntryRejectReason

instance GenValid LastMsgSeqNumProcessed

instance GenValid RefTagID

instance GenValid RefMsgType

instance GenValid SessionRejectReason

instance GenValid BidRequestTransType

instance GenValid ContraBroker

instance GenValid ComplianceID

instance GenValid SolicitedFlag

instance GenValid ExecRestatementReason

instance GenValid BusinessRejectRefID

instance GenValid BusinessRejectReason

instance GenValid GrossTradeAmt

instance GenValid NoContraBrokers

instance GenValid MaxMessageSize

instance GenValid NoMsgTypes

instance GenValid MsgDirection

instance GenValid NoTradingSessions

instance GenValid TotalVolumeTraded

instance GenValid DiscretionInst

instance GenValid DiscretionOffsetValue

instance GenValid BidID

instance GenValid ClientBidID

instance GenValid ListName

instance GenValid TotNoRelatedSym

instance GenValid BidType

instance GenValid NumTickets

instance GenValid SideValue1

instance GenValid SideValue2

instance GenValid NoBidDescriptors

instance GenValid BidDescriptorType

instance GenValid BidDescriptor

instance GenValid SideValueInd

instance GenValid LiquidityPctLow

instance GenValid LiquidityPctHigh

instance GenValid LiquidityValue

instance GenValid EFPTrackingError

instance GenValid FairValue

instance GenValid OutsideIndexPct

instance GenValid ValueOfFutures

instance GenValid LiquidityIndType

instance GenValid WtAverageLiquidity

instance GenValid ExchangeForPhysical

instance GenValid OutMainCntryUIndex

instance GenValid CrossPercent

instance GenValid ProgRptReqs

instance GenValid ProgPeriodInterval

instance GenValid IncTaxInd

instance GenValid NumBidders

instance GenValid BidTradeType

instance GenValid BasisPxType

instance GenValid NoBidComponents

instance GenValid Country

instance GenValid TotNoStrikes

instance GenValid PriceType

instance GenValid DayOrderQty

instance GenValid DayCumQty

instance GenValid DayAvgPx

instance GenValid GTBookingInst

instance GenValid NoStrikes

instance GenValid ListStatusType

instance GenValid NetGrossInd

instance GenValid ListOrderStatus

instance GenValid ExpireDate

instance GenValid ListExecInstType

instance GenValid CxlRejResponseTo

instance GenValid UnderlyingCouponRate

instance GenValid UnderlyingContractMultiplier

instance GenValid ContraTradeQty

instance GenValid ContraTradeTime

instance GenValid LiquidityNumSecurities

instance GenValid MultiLegReportingType

instance GenValid StrikeTime

instance GenValid ListStatusText

instance GenValid EncodedListStatusTextLen

instance GenValid EncodedListStatusText

instance GenValid PartyIDSource

instance GenValid PartyID

instance GenValid NetChgPrevDay

instance GenValid PartyRole

instance GenValid NoPartyIDs

instance GenValid NoSecurityAltID

instance GenValid SecurityAltID

instance GenValid SecurityAltIDSource

instance GenValid NoUnderlyingSecurityAltID

instance GenValid UnderlyingSecurityAltID

instance GenValid UnderlyingSecurityAltIDSource

instance GenValid Product

instance GenValid CFICode

instance GenValid UnderlyingProduct

instance GenValid UnderlyingCFICode

instance GenValid TestMessageIndicator

instance GenValid BookingRefID

instance GenValid IndividualAllocID

instance GenValid RoundingDirection

instance GenValid RoundingModulus

instance GenValid CountryOfIssue

instance GenValid StateOrProvinceOfIssue

instance GenValid LocaleOfIssue

instance GenValid NoRegistDtls

instance GenValid MailingDtls

instance GenValid InvestorCountryOfResidence

instance GenValid PaymentRef

instance GenValid DistribPaymentMethod

instance GenValid CashDistribCurr

instance GenValid CommCurrency

instance GenValid CancellationRights

instance GenValid MoneyLaunderingStatus

instance GenValid MailingInst

instance GenValid TransBkdTime

instance GenValid ExecPriceType

instance GenValid ExecPriceAdjustment

instance GenValid DateOfBirth

instance GenValid TradeReportTransType

instance GenValid CardHolderName

instance GenValid CardNumber

instance GenValid CardExpDate

instance GenValid CardIssNum

instance GenValid PaymentMethod

instance GenValid RegistAcctType

instance GenValid Designation

instance GenValid TaxAdvantageType

instance GenValid RegistRejReasonText

instance GenValid FundRenewWaiv

instance GenValid CashDistribAgentName

instance GenValid CashDistribAgentCode

instance GenValid CashDistribAgentAcctNumber

instance GenValid CashDistribPayRef

instance GenValid CashDistribAgentAcctName

instance GenValid CardStartDate

instance GenValid PaymentDate

instance GenValid PaymentRemitterID

instance GenValid RegistStatus

instance GenValid RegistRejReasonCode

instance GenValid RegistRefID

instance GenValid RegistDtls

instance GenValid NoDistribInsts

instance GenValid RegistEmail

instance GenValid DistribPercentage

instance GenValid RegistID

instance GenValid RegistTransType

instance GenValid ExecValuationPoint

instance GenValid OrderPercent

instance GenValid OwnershipType

instance GenValid NoContAmts

instance GenValid ContAmtType

instance GenValid ContAmtValue

instance GenValid ContAmtCurr

instance GenValid OwnerType

instance GenValid PartySubID

instance GenValid NestedPartyID

instance GenValid NestedPartyIDSource

instance GenValid SecondaryClOrdID

instance GenValid SecondaryExecID

instance GenValid OrderCapacity

instance GenValid OrderRestrictions

instance GenValid MassCancelRequestType

instance GenValid MassCancelResponse

instance GenValid MassCancelRejectReason

instance GenValid TotalAffectedOrders

instance GenValid NoAffectedOrders

instance GenValid AffectedOrderID

instance GenValid AffectedSecondaryOrderID

instance GenValid QuoteType

instance GenValid NestedPartyRole

instance GenValid NoNestedPartyIDs

instance GenValid TotalAccruedInterestAmt

instance GenValid MaturityDate

instance GenValid UnderlyingMaturityDate

instance GenValid InstrRegistry

instance GenValid CashMargin

instance GenValid NestedPartySubID

instance GenValid Scope

instance GenValid MDImplicitDelete

instance GenValid CrossID

instance GenValid CrossType

instance GenValid CrossPrioritization

instance GenValid OrigCrossID

instance GenValid NoSides

instance GenValid Username

instance GenValid Password

instance GenValid NoLegs

instance GenValid LegCurrency

instance GenValid TotNoSecurityTypes

instance GenValid NoSecurityTypes

instance GenValid SecurityListRequestType

instance GenValid SecurityRequestResult

instance GenValid RoundLot

instance GenValid MinTradeVol

instance GenValid MultiLegRptTypeReq

instance GenValid LegPositionEffect

instance GenValid LegCoveredOrUncovered

instance GenValid LegPrice

instance GenValid TradSesStatusRejReason

instance GenValid TradeRequestID

instance GenValid TradeRequestType

instance GenValid PreviouslyReported

instance GenValid TradeReportID

instance GenValid TradeReportRefID

instance GenValid MatchStatus

instance GenValid MatchType

instance GenValid OddLot

instance GenValid NoClearingInstructions

instance GenValid ClearingInstruction

instance GenValid TradeInputSource

instance GenValid TradeInputDevice

instance GenValid NoDates

instance GenValid AccountType

instance GenValid CustOrderCapacity

instance GenValid ClOrdLinkID

instance GenValid MassStatusReqID

instance GenValid MassStatusReqType

instance GenValid OrigOrdModTime

instance GenValid LegSettlType

instance GenValid LegSettlDate

instance GenValid DayBookingInst

instance GenValid BookingUnit

instance GenValid PreallocMethod

instance GenValid UnderlyingCountryOfIssue

instance GenValid UnderlyingStateOrProvinceOfIssue

instance GenValid UnderlyingLocaleOfIssue

instance GenValid UnderlyingInstrRegistry

instance GenValid LegCountryOfIssue

instance GenValid LegStateOrProvinceOfIssue

instance GenValid LegLocaleOfIssue

instance GenValid LegInstrRegistry

instance GenValid LegSymbol

instance GenValid LegSymbolSfx

instance GenValid LegSecurityID

instance GenValid LegSecurityIDSource

instance GenValid NoLegSecurityAltID

instance GenValid LegSecurityAltID

instance GenValid LegSecurityAltIDSource

instance GenValid LegProduct

instance GenValid LegCFICode

instance GenValid LegSecurityType

instance GenValid LegMaturityMonthYear

instance GenValid LegMaturityDate

instance GenValid LegStrikePrice

instance GenValid LegOptAttribute

instance GenValid LegContractMultiplier

instance GenValid LegCouponRate

instance GenValid LegSecurityExchange

instance GenValid LegIssuer

instance GenValid EncodedLegIssuerLen

instance GenValid EncodedLegIssuer

instance GenValid LegSecurityDesc

instance GenValid EncodedLegSecurityDescLen

instance GenValid EncodedLegSecurityDesc

instance GenValid LegRatioQty

instance GenValid LegSide

instance GenValid TradingSessionSubID

instance GenValid AllocType

instance GenValid NoHops

instance GenValid HopCompID

instance GenValid HopSendingTime

instance GenValid HopRefID

instance GenValid MidPx

instance GenValid BidYield

instance GenValid MidYield

instance GenValid OfferYield

instance GenValid ClearingFeeIndicator

instance GenValid WorkingIndicator

instance GenValid LegLastPx

instance GenValid PriorityIndicator

instance GenValid PriceImprovement

instance GenValid Price2

instance GenValid LastForwardPoints2

instance GenValid BidForwardPoints2

instance GenValid OfferForwardPoints2

instance GenValid RFQReqID

instance GenValid MktBidPx

instance GenValid MktOfferPx

instance GenValid MinBidSize

instance GenValid MinOfferSize

instance GenValid QuoteStatusReqID

instance GenValid LegalConfirm

instance GenValid UnderlyingLastPx

instance GenValid UnderlyingLastQty

instance GenValid LegRefID

instance GenValid ContraLegRefID

instance GenValid SettlCurrBidFxRate

instance GenValid SettlCurrOfferFxRate

instance GenValid QuoteRequestRejectReason

instance GenValid SideComplianceID

instance GenValid AcctIDSource

instance GenValid AllocAcctIDSource

instance GenValid BenchmarkPrice

instance GenValid BenchmarkPriceType

instance GenValid ConfirmID

instance GenValid ConfirmStatus

instance GenValid ConfirmTransType

instance GenValid ContractSettlMonth

instance GenValid DeliveryForm

instance GenValid LastParPx

instance GenValid NoLegAllocs

instance GenValid LegAllocAccount

instance GenValid LegIndividualAllocID

instance GenValid LegAllocQty

instance GenValid LegAllocAcctIDSource

instance GenValid LegSettlCurrency

instance GenValid LegBenchmarkCurveCurrency

instance GenValid LegBenchmarkCurveName

instance GenValid LegBenchmarkCurvePoint

instance GenValid LegBenchmarkPrice

instance GenValid LegBenchmarkPriceType

instance GenValid LegBidPx

instance GenValid LegIOIQty

instance GenValid NoLegStipulations

instance GenValid LegOfferPx

instance GenValid LegPriceType

instance GenValid LegQty

instance GenValid LegStipulationType

instance GenValid LegStipulationValue

instance GenValid LegSwapType

instance GenValid Pool

instance GenValid QuotePriceType

instance GenValid QuoteRespID

instance GenValid QuoteRespType

instance GenValid QuoteQualifier

instance GenValid YieldRedemptionDate

instance GenValid YieldRedemptionPrice

instance GenValid YieldRedemptionPriceType

instance GenValid BenchmarkSecurityID

instance GenValid ReversalIndicator

instance GenValid YieldCalcDate

instance GenValid NoPositions

instance GenValid PosType

instance GenValid LongQty

instance GenValid ShortQty

instance GenValid PosQtyStatus

instance GenValid PosAmtType

instance GenValid PosAmt

instance GenValid PosTransType

instance GenValid PosReqID

instance GenValid NoUnderlyings

instance GenValid PosMaintAction

instance GenValid OrigPosReqRefID

instance GenValid PosMaintRptRefID

instance GenValid ClearingBusinessDate

instance GenValid SettlSessID

instance GenValid SettlSessSubID

instance GenValid AdjustmentType

instance GenValid ContraryInstructionIndicator

instance GenValid PriorSpreadIndicator

instance GenValid PosMaintRptID

instance GenValid PosMaintStatus

instance GenValid PosMaintResult

instance GenValid PosReqType

instance GenValid ResponseTransportType

instance GenValid ResponseDestination

instance GenValid TotalNumPosReports

instance GenValid PosReqResult

instance GenValid PosReqStatus

instance GenValid SettlPrice

instance GenValid SettlPriceType

instance GenValid UnderlyingSettlPrice

instance GenValid UnderlyingSettlPriceType

instance GenValid PriorSettlPrice

instance GenValid NoQuoteQualifiers

instance GenValid AllocSettlCurrency

instance GenValid AllocSettlCurrAmt

instance GenValid InterestAtMaturity

instance GenValid LegDatedDate

instance GenValid LegPool

instance GenValid AllocInterestAtMaturity

instance GenValid AllocAccruedInterestAmt

instance GenValid DeliveryDate

instance GenValid AssignmentMethod

instance GenValid AssignmentUnit

instance GenValid OpenInterest

instance GenValid ExerciseMethod

instance GenValid TotNumTradeReports

instance GenValid TradeRequestResult

instance GenValid TradeRequestStatus

instance GenValid TradeReportRejectReason

instance GenValid SideMultiLegReportingType

instance GenValid NoPosAmt

instance GenValid AutoAcceptIndicator

instance GenValid AllocReportID

instance GenValid NoNested2PartyIDs

instance GenValid Nested2PartyID

instance GenValid Nested2PartyIDSource

instance GenValid Nested2PartyRole

instance GenValid Nested2PartySubID

instance GenValid BenchmarkSecurityIDSource

instance GenValid SecuritySubType

instance GenValid UnderlyingSecuritySubType

instance GenValid LegSecuritySubType

instance GenValid AllowableOneSidednessPct

instance GenValid AllowableOneSidednessValue

instance GenValid AllowableOneSidednessCurr

instance GenValid NoTrdRegTimestamps

instance GenValid TrdRegTimestamp

instance GenValid TrdRegTimestampType

instance GenValid TrdRegTimestampOrigin

instance GenValid ConfirmRefID

instance GenValid ConfirmType

instance GenValid ConfirmRejReason

instance GenValid BookingType

instance GenValid IndividualAllocRejCode

instance GenValid SettlInstMsgID

instance GenValid NoSettlInst

instance GenValid LastUpdateTime

instance GenValid AllocSettlInstType

instance GenValid NoSettlPartyIDs

instance GenValid SettlPartyID

instance GenValid SettlPartyIDSource

instance GenValid SettlPartyRole

instance GenValid SettlPartySubID

instance GenValid SettlPartySubIDType

instance GenValid DlvyInstType

instance GenValid TerminationType

instance GenValid NextExpectedMsgSeqNum

instance GenValid OrdStatusReqID

instance GenValid SettlInstReqID

instance GenValid SettlInstReqRejCode

instance GenValid SecondaryAllocID

instance GenValid AllocReportType

instance GenValid AllocReportRefID

instance GenValid AllocCancReplaceReason

instance GenValid CopyMsgIndicator

instance GenValid AllocAccountType

instance GenValid OrderAvgPx

instance GenValid OrderBookingQty

instance GenValid NoSettlPartySubIDs

instance GenValid NoPartySubIDs

instance GenValid PartySubIDType

instance GenValid NoNestedPartySubIDs

instance GenValid NestedPartySubIDType

instance GenValid NoNested2PartySubIDs

instance GenValid Nested2PartySubIDType

instance GenValid AllocIntermedReqType

instance GenValid UnderlyingPx

instance GenValid PriceDelta

instance GenValid ApplQueueMax

instance GenValid ApplQueueDepth

instance GenValid ApplQueueResolution

instance GenValid ApplQueueAction

instance GenValid NoAltMDSource

instance GenValid AltMDSourceID

instance GenValid SecondaryTradeReportID

instance GenValid AvgPxIndicator

instance GenValid TradeLinkID

instance GenValid OrderInputDevice

instance GenValid UnderlyingTradingSessionID

instance GenValid UnderlyingTradingSessionSubID

instance GenValid TradeLegRefID

instance GenValid ExchangeRule

instance GenValid TradeAllocIndicator

instance GenValid ExpirationCycle

instance GenValid TrdType

instance GenValid TrdSubType

instance GenValid TransferReason

instance GenValid TotNumAssignmentReports

instance GenValid AsgnRptID

instance GenValid ThresholdAmount

instance GenValid PegMoveType

instance GenValid PegOffsetType

instance GenValid PegLimitType

instance GenValid PegRoundDirection

instance GenValid PeggedPrice

instance GenValid PegScope

instance GenValid DiscretionMoveType

instance GenValid DiscretionOffsetType

instance GenValid DiscretionLimitType

instance GenValid DiscretionRoundDirection

instance GenValid DiscretionPrice

instance GenValid DiscretionScope

instance GenValid TargetStrategy

instance GenValid TargetStrategyParameters

instance GenValid ParticipationRate

instance GenValid TargetStrategyPerformance

instance GenValid LastLiquidityInd

instance GenValid PublishTrdIndicator

instance GenValid ShortSaleReason

instance GenValid QtyType

instance GenValid SecondaryTrdType

instance GenValid TradeReportType

instance GenValid AllocNoOrdersType

instance GenValid SharedCommission

instance GenValid ConfirmReqID

instance GenValid AvgParPx

instance GenValid ReportedPx

instance GenValid NoCapacities

instance GenValid OrderCapacityQty

instance GenValid NoEvents

instance GenValid EventType

instance GenValid EventDate

instance GenValid EventPx

instance GenValid EventText

instance GenValid PctAtRisk

instance GenValid NoInstrAttrib

instance GenValid InstrAttribType

instance GenValid InstrAttribValue

instance GenValid DatedDate

instance GenValid InterestAccrualDate

instance GenValid CPProgram

instance GenValid CPRegType

instance GenValid UnderlyingCPProgram

instance GenValid UnderlyingCPRegType

instance GenValid UnderlyingQty

instance GenValid TrdMatchID

instance GenValid SecondaryTradeReportRefID

instance GenValid UnderlyingDirtyPrice

instance GenValid UnderlyingEndPrice

instance GenValid UnderlyingStartValue

instance GenValid UnderlyingCurrentValue

instance GenValid UnderlyingEndValue

instance GenValid NoUnderlyingStips

instance GenValid UnderlyingStipType

instance GenValid UnderlyingStipValue

instance GenValid MaturityNetMoney

instance GenValid MiscFeeBasis

instance GenValid TotNoAllocs

instance GenValid LastFragment

instance GenValid CollReqID

instance GenValid CollAsgnReason

instance GenValid CollInquiryQualifier

instance GenValid NoTrades

instance GenValid MarginRatio

instance GenValid MarginExcess

instance GenValid TotalNetValue

instance GenValid CashOutstanding

instance GenValid CollAsgnID

instance GenValid CollAsgnTransType

instance GenValid CollRespID

instance GenValid CollAsgnRespType

instance GenValid CollAsgnRejectReason

instance GenValid CollAsgnRefID

instance GenValid CollRptID

instance GenValid CollInquiryID

instance GenValid CollStatus

instance GenValid TotNumReports

instance GenValid LastRptRequested

instance GenValid AgreementDesc

instance GenValid AgreementID

instance GenValid AgreementDate

instance GenValid StartDate

instance GenValid EndDate

instance GenValid AgreementCurrency

instance GenValid DeliveryType

instance GenValid EndAccruedInterestAmt

instance GenValid StartCash

instance GenValid EndCash

instance GenValid UserRequestID

instance GenValid UserRequestType

instance GenValid NewPassword

instance GenValid UserStatus

instance GenValid UserStatusText

instance GenValid StatusValue

instance GenValid StatusText

instance GenValid RefCompID

instance GenValid RefSubID

instance GenValid NetworkResponseID

instance GenValid NetworkRequestID

instance GenValid LastNetworkResponseID

instance GenValid NetworkRequestType

instance GenValid NoCompIDs

instance GenValid NetworkStatusResponseType

instance GenValid NoCollInquiryQualifier

instance GenValid TrdRptStatus

instance GenValid AffirmStatus

instance GenValid UnderlyingStrikeCurrency

instance GenValid LegStrikeCurrency

instance GenValid TimeBracket

instance GenValid CollAction

instance GenValid CollInquiryStatus

instance GenValid CollInquiryResult

instance GenValid StrikeCurrency

instance GenValid NoNested3PartyIDs

instance GenValid Nested3PartyID

instance GenValid Nested3PartyIDSource

instance GenValid Nested3PartyRole

instance GenValid NoNested3PartySubIDs

instance GenValid Nested3PartySubID

instance GenValid Nested3PartySubIDType

instance GenValid LegContractSettlMonth

instance GenValid LegInterestAccrualDate
