{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Messages.CollateralRequest where

import Data.Validity
import FIX.Fields.Account
import FIX.Fields.AccountType
import FIX.Fields.AccruedInterestAmt
import FIX.Fields.CashOutstanding
import FIX.Fields.ClOrdID
import FIX.Fields.ClearingBusinessDate
import FIX.Fields.CollAsgnReason
import FIX.Fields.CollReqID
import FIX.Fields.Currency
import FIX.Fields.EncodedText
import FIX.Fields.EncodedTextLen
import FIX.Fields.EndAccruedInterestAmt
import FIX.Fields.EndCash
import FIX.Fields.ExpireTime
import FIX.Fields.MarginExcess
import FIX.Fields.OrderID
import FIX.Fields.Price
import FIX.Fields.PriceType
import FIX.Fields.QtyType
import FIX.Fields.Quantity
import FIX.Fields.SecondaryClOrdID
import FIX.Fields.SecondaryOrderID
import FIX.Fields.SettlDate
import FIX.Fields.SettlSessID
import FIX.Fields.SettlSessSubID
import FIX.Fields.Side
import FIX.Fields.StartCash
import FIX.Fields.Text
import FIX.Fields.TotalNetValue
import FIX.Fields.TradingSessionID
import FIX.Fields.TradingSessionSubID
import FIX.Fields.TransactTime
import GHC.Generics (Generic)

-- MessageSpec {messageName = "CollateralRequest", messageType = "AX", messageCategory = "app", messagePieces = [MessagePieceField "CollReqID" True,MessagePieceField "CollAsgnReason" True,MessagePieceField "TransactTime" True,MessagePieceField "ExpireTime" False,MessagePieceComponent "Parties" False,MessagePieceField "Account" False,MessagePieceField "AccountType" False,MessagePieceField "ClOrdID" False,MessagePieceField "OrderID" False,MessagePieceField "SecondaryOrderID" False,MessagePieceField "SecondaryClOrdID" False,MessagePieceComponent "ExecCollGrp" False,MessagePieceComponent "TrdCollGrp" False,MessagePieceComponent "Instrument" False,MessagePieceComponent "FinancingDetails" False,MessagePieceField "SettlDate" False,MessagePieceField "Quantity" False,MessagePieceField "QtyType" False,MessagePieceField "Currency" False,MessagePieceComponent "InstrmtLegGrp" False,MessagePieceComponent "UndInstrmtCollGrp" False,MessagePieceField "MarginExcess" False,MessagePieceField "TotalNetValue" False,MessagePieceField "CashOutstanding" False,MessagePieceComponent "TrdRegTimestamps" False,MessagePieceField "Side" False,MessagePieceComponent "MiscFeesGrp" False,MessagePieceField "Price" False,MessagePieceField "PriceType" False,MessagePieceField "AccruedInterestAmt" False,MessagePieceField "EndAccruedInterestAmt" False,MessagePieceField "StartCash" False,MessagePieceField "EndCash" False,MessagePieceComponent "SpreadOrBenchmarkCurveData" False,MessagePieceComponent "Stipulations" False,MessagePieceField "TradingSessionID" False,MessagePieceField "TradingSessionSubID" False,MessagePieceField "SettlSessID" False,MessagePieceField "SettlSessSubID" False,MessagePieceField "ClearingBusinessDate" False,MessagePieceField "Text" False,MessagePieceField "EncodedTextLen" False,MessagePieceField "EncodedText" False]}
data CollateralRequest = CollateralRequest
  { collateralRequestCollReqID :: !CollReqID,
    collateralRequestCollAsgnReason :: !CollAsgnReason,
    collateralRequestTransactTime :: !TransactTime,
    collateralRequestExpireTime :: !(Maybe ExpireTime),
    collateralRequestAccount :: !(Maybe Account),
    collateralRequestAccountType :: !(Maybe AccountType),
    collateralRequestClOrdID :: !(Maybe ClOrdID),
    collateralRequestOrderID :: !(Maybe OrderID),
    collateralRequestSecondaryOrderID :: !(Maybe SecondaryOrderID),
    collateralRequestSecondaryClOrdID :: !(Maybe SecondaryClOrdID),
    collateralRequestSettlDate :: !(Maybe SettlDate),
    collateralRequestQuantity :: !(Maybe Quantity),
    collateralRequestQtyType :: !(Maybe QtyType),
    collateralRequestCurrency :: !(Maybe Currency),
    collateralRequestMarginExcess :: !(Maybe MarginExcess),
    collateralRequestTotalNetValue :: !(Maybe TotalNetValue),
    collateralRequestCashOutstanding :: !(Maybe CashOutstanding),
    collateralRequestSide :: !(Maybe Side),
    collateralRequestPrice :: !(Maybe Price),
    collateralRequestPriceType :: !(Maybe PriceType),
    collateralRequestAccruedInterestAmt :: !(Maybe AccruedInterestAmt),
    collateralRequestEndAccruedInterestAmt :: !(Maybe EndAccruedInterestAmt),
    collateralRequestStartCash :: !(Maybe StartCash),
    collateralRequestEndCash :: !(Maybe EndCash),
    collateralRequestTradingSessionID :: !(Maybe TradingSessionID),
    collateralRequestTradingSessionSubID :: !(Maybe TradingSessionSubID),
    collateralRequestSettlSessID :: !(Maybe SettlSessID),
    collateralRequestSettlSessSubID :: !(Maybe SettlSessSubID),
    collateralRequestClearingBusinessDate :: !(Maybe ClearingBusinessDate),
    collateralRequestText :: !(Maybe Text),
    collateralRequestEncodedTextLen :: !(Maybe EncodedTextLen),
    collateralRequestEncodedText :: !(Maybe EncodedText)
  }
  deriving stock (Show, Eq, Generic)

instance Validity CollateralRequest
