{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Messages.PositionReport where

import Data.Validity
import FIX.Fields.Account
import FIX.Fields.AccountType
import FIX.Fields.AcctIDSource
import FIX.Fields.ClearingBusinessDate
import FIX.Fields.Currency
import FIX.Fields.DeliveryDate
import FIX.Fields.EncodedText
import FIX.Fields.EncodedTextLen
import FIX.Fields.PosMaintRptID
import FIX.Fields.PosReqID
import FIX.Fields.PosReqResult
import FIX.Fields.PosReqType
import FIX.Fields.PriorSettlPrice
import FIX.Fields.RegistStatus
import FIX.Fields.SettlPrice
import FIX.Fields.SettlPriceType
import FIX.Fields.SettlSessID
import FIX.Fields.SettlSessSubID
import FIX.Fields.SubscriptionRequestType
import FIX.Fields.Text
import FIX.Fields.TotalNumPosReports
import FIX.Fields.UnsolicitedIndicator
import GHC.Generics (Generic)

-- MessageSpec {messageName = "PositionReport", messageType = "AP", messageCategory = "app", messagePieces = [MessagePieceField "PosMaintRptID" True,MessagePieceField "PosReqID" False,MessagePieceField "PosReqType" False,MessagePieceField "SubscriptionRequestType" False,MessagePieceField "TotalNumPosReports" False,MessagePieceField "UnsolicitedIndicator" False,MessagePieceField "PosReqResult" True,MessagePieceField "ClearingBusinessDate" True,MessagePieceField "SettlSessID" False,MessagePieceField "SettlSessSubID" False,MessagePieceComponent "Parties" True,MessagePieceField "Account" True,MessagePieceField "AcctIDSource" False,MessagePieceField "AccountType" True,MessagePieceComponent "Instrument" False,MessagePieceField "Currency" False,MessagePieceField "SettlPrice" True,MessagePieceField "SettlPriceType" True,MessagePieceField "PriorSettlPrice" True,MessagePieceComponent "InstrmtLegGrp" False,MessagePieceComponent "PosUndInstrmtGrp" False,MessagePieceComponent "PositionQty" True,MessagePieceComponent "PositionAmountData" True,MessagePieceField "RegistStatus" False,MessagePieceField "DeliveryDate" False,MessagePieceField "Text" False,MessagePieceField "EncodedTextLen" False,MessagePieceField "EncodedText" False]}
data PositionReport = PositionReport
  { positionReportPosMaintRptID :: !PosMaintRptID,
    positionReportPosReqID :: !(Maybe PosReqID),
    positionReportPosReqType :: !(Maybe PosReqType),
    positionReportSubscriptionRequestType :: !(Maybe SubscriptionRequestType),
    positionReportTotalNumPosReports :: !(Maybe TotalNumPosReports),
    positionReportUnsolicitedIndicator :: !(Maybe UnsolicitedIndicator),
    positionReportPosReqResult :: !PosReqResult,
    positionReportClearingBusinessDate :: !ClearingBusinessDate,
    positionReportSettlSessID :: !(Maybe SettlSessID),
    positionReportSettlSessSubID :: !(Maybe SettlSessSubID),
    positionReportAccount :: !Account,
    positionReportAcctIDSource :: !(Maybe AcctIDSource),
    positionReportAccountType :: !AccountType,
    positionReportCurrency :: !(Maybe Currency),
    positionReportSettlPrice :: !SettlPrice,
    positionReportSettlPriceType :: !SettlPriceType,
    positionReportPriorSettlPrice :: !PriorSettlPrice,
    positionReportRegistStatus :: !(Maybe RegistStatus),
    positionReportDeliveryDate :: !(Maybe DeliveryDate),
    positionReportText :: !(Maybe Text),
    positionReportEncodedTextLen :: !(Maybe EncodedTextLen),
    positionReportEncodedText :: !(Maybe EncodedText)
  }
  deriving stock (Show, Eq, Generic)

instance Validity PositionReport
