{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Messages.QuoteRequest where

import Data.List.NonEmpty (NonEmpty)
import Data.Proxy
import Data.Validity
import FIX.Components.Class
import FIX.Components.Parties
import FIX.Fields.AvgPxPrecision
import FIX.Fields.ClOrdID
import FIX.Fields.DayCount
import FIX.Fields.EncodedText
import FIX.Fields.ExecutionVenueType
import FIX.Fields.ExpireTime
import FIX.Fields.FarLegRatePrecision
import FIX.Fields.Fiduciary
import FIX.Fields.FixingReference
import FIX.Fields.ForwardPointsPrecision
import FIX.Fields.ForwardRatePrecision
import FIX.Fields.InterestRatePrecision
import FIX.Fields.LastCapacity
import FIX.Fields.MsgType
import FIX.Fields.NearLegRatePrecision
import FIX.Fields.OptionDate
import FIX.Fields.OrdType
import FIX.Fields.OrderCapacity
import FIX.Fields.ProductType
import FIX.Fields.QuoteReqID
import FIX.Fields.RFQReqID
import FIX.Fields.RefSpotDate
import FIX.Fields.SpotRatePrecision
import FIX.Fields.Text
import FIX.Fields.Username
import FIX.Groups.Class
import FIX.Groups.CustomFieldsGroupElem
import FIX.Groups.OrderAttributesGroupElem
import FIX.Groups.RegulatoryTradeIDsGroupElem
import FIX.Groups.RelatedSymGroupElem
import FIX.Messages.Class
import GHC.Generics (Generic)

-- | MessageSpec
--   { messageName = "QuoteRequest"
--   , messageType = "R"
--   , messageCategory = "app"
--   , messagePieces =
--       [ MessagePieceField "QuoteReqID" True
--       , MessagePieceField "RFQReqID" False
--       , MessagePieceField "ClOrdID" False
--       , MessagePieceField "OrderCapacity" False
--       , MessagePieceField "Username" False
--       , MessagePieceGroup
--           GroupSpec
--             { groupName = "NoRelatedSym"
--             , groupNumberField = "NoRelatedSym"
--             , groupPieces =
--                 [ MessagePieceComponent "Instrument" True
--                 , MessagePieceComponent "FinancingDetails" True
--                 , MessagePieceGroup
--                     GroupSpec
--                       { groupName = "NoUnderlyings"
--                       , groupNumberField = "NoUnderlyings"
--                       , groupPieces =
--                           [ MessagePieceComponent "UnderlyingInstrument" True ]
--                       }
--                     False
--                 , MessagePieceField "PrevClosePx" False
--                 , MessagePieceField "QuoteRequestType" False
--                 , MessagePieceField "QuoteType" False
--                 , MessagePieceField "TradingSessionID" False
--                 , MessagePieceField "TradingSessionSubID" False
--                 , MessagePieceField "TradeOriginationDate" False
--                 , MessagePieceField "Side" False
--                 , MessagePieceField "QtyType" False
--                 , MessagePieceComponent "OrderQtyData" True
--                 , MessagePieceField "SettlType" False
--                 , MessagePieceField "SettlDate" False
--                 , MessagePieceField "SplitSettlDate" False
--                 , MessagePieceField "SettlDate2" False
--                 , MessagePieceField "SplitSettlDate2" False
--                 , MessagePieceField "OrderQty2" False
--                 , MessagePieceField "Currency" False
--                 , MessagePieceComponent "Stipulations" True
--                 , MessagePieceField "Account" False
--                 , MessagePieceField "Username" False
--                 , MessagePieceField "AcctIDSource" False
--                 , MessagePieceField "AccountType" False
--                 , MessagePieceGroup
--                     GroupSpec
--                       { groupName = "NoQuoteQualifiers"
--                       , groupNumberField = "NoQuoteQualifiers"
--                       , groupPieces = [ MessagePieceField "QuoteQualifier" True ]
--                       }
--                     False
--                 , MessagePieceField "QuotePriceType" False
--                 , MessagePieceField "OrdType" False
--                 , MessagePieceField "ValidUntilTime" False
--                 , MessagePieceField "ExpireTime" False
--                 , MessagePieceField "TransactTime" False
--                 , MessagePieceComponent "SpreadOrBenchmarkCurveData" True
--                 , MessagePieceField "PriceType" False
--                 , MessagePieceField "Price" False
--                 , MessagePieceField "Price2" False
--                 , MessagePieceComponent "YieldData" True
--                 , MessagePieceGroup
--                     GroupSpec
--                       { groupName = "NoAllocs"
--                       , groupNumberField = "NoAllocs"
--                       , groupPieces =
--                           [ MessagePieceField "AllocAccount" True
--                           , MessagePieceField "AllocQty" True
--                           ]
--                       }
--                     False
--                 , MessagePieceGroup
--                     GroupSpec
--                       { groupName = "NoLegs"
--                       , groupNumberField = "NoLegs"
--                       , groupPieces =
--                           [ MessagePieceField "LegSymbol" True
--                           , MessagePieceField "LegMaturityDate" False
--                           , MessagePieceField "LegSide" True
--                           , MessagePieceField "LegQty" True
--                           , MessagePieceGroup
--                               GroupSpec
--                                 { groupName = "NoLegAllocs"
--                                 , groupNumberField = "NoLegAllocs"
--                                 , groupPieces =
--                                     [ MessagePieceField "LegAllocAccount" True
--                                     , MessagePieceField "LegAllocQty" True
--                                     , MessagePieceComponent "NestedParties" True
--                                     ]
--                                 }
--                               False
--                           , MessagePieceField "LegRefID" True
--                           , MessagePieceField "LegSettlDate" True
--                           , MessagePieceField "LegSplitSettlDate" False
--                           ]
--                       }
--                     False
--                 ]
--             }
--           True
--       , MessagePieceComponent "Parties" True
--       , MessagePieceGroup
--           GroupSpec
--             { groupName = "NoRegulatoryTradeIDs"
--             , groupNumberField = "NoRegulatoryTradeIDs"
--             , groupPieces =
--                 [ MessagePieceField "RegulatoryTradeID" True
--                 , MessagePieceField "RegulatoryTradeIDType" False
--                 ]
--             }
--           False
--       , MessagePieceGroup
--           GroupSpec
--             { groupName = "NoOrderAttributes"
--             , groupNumberField = "NoOrderAttributes"
--             , groupPieces =
--                 [ MessagePieceField "OrderAttributeType" True
--                 , MessagePieceField "OrderAttributeValue" False
--                 ]
--             }
--           False
--       , MessagePieceField "OptionDate" False
--       , MessagePieceField "Text" False
--       , MessagePieceField "EncodedText" False
--       , MessagePieceField "RefSpotDate" False
--       , MessagePieceField "ProductType" False
--       , MessagePieceField "ExecutionVenueType" False
--       , MessagePieceField "LastCapacity" False
--       , MessagePieceField "DayCount" False
--       , MessagePieceField "FixingReference" False
--       , MessagePieceField "AvgPxPrecision" False
--       , MessagePieceField "ExpireTime" False
--       , MessagePieceField "Fiduciary" False
--       , MessagePieceField "OrdType" False
--       , MessagePieceField "SpotRatePrecision" False
--       , MessagePieceField "ForwardRatePrecision" False
--       , MessagePieceField "ForwardPointsPrecision" False
--       , MessagePieceField "InterestRatePrecision" False
--       , MessagePieceField "NearLegRatePrecision" False
--       , MessagePieceField "FarLegRatePrecision" False
--       , MessagePieceGroup
--           GroupSpec
--             { groupName = "NoCustomFields"
--             , groupNumberField = "NoCustomFields"
--             , groupPieces =
--                 [ MessagePieceField "CustomFieldsName" True
--                 , MessagePieceField "CustomFieldsValue" False
--                 ]
--             }
--           False
--       ]
--   }
data QuoteRequest = QuoteRequest
  { quoteRequestQuoteReqID :: !QuoteReqID,
    quoteRequestRFQReqID :: !(Maybe RFQReqID),
    quoteRequestClOrdID :: !(Maybe ClOrdID),
    quoteRequestOrderCapacity :: !(Maybe OrderCapacity),
    quoteRequestUsername :: !(Maybe Username),
    quoteRequestRelatedSymGroup :: !(NonEmpty RelatedSymGroupElem),
    quoteRequestParties :: !Parties,
    quoteRequestRegulatoryTradeIDsGroup :: ![RegulatoryTradeIDsGroupElem],
    quoteRequestOrderAttributesGroup :: ![OrderAttributesGroupElem],
    quoteRequestOptionDate :: !(Maybe OptionDate),
    quoteRequestText :: !(Maybe Text),
    quoteRequestEncodedText :: !(Maybe EncodedText),
    quoteRequestRefSpotDate :: !(Maybe RefSpotDate),
    quoteRequestProductType :: !(Maybe ProductType),
    quoteRequestExecutionVenueType :: !(Maybe ExecutionVenueType),
    quoteRequestLastCapacity :: !(Maybe LastCapacity),
    quoteRequestDayCount :: !(Maybe DayCount),
    quoteRequestFixingReference :: !(Maybe FixingReference),
    quoteRequestAvgPxPrecision :: !(Maybe AvgPxPrecision),
    quoteRequestExpireTime :: !(Maybe ExpireTime),
    quoteRequestFiduciary :: !(Maybe Fiduciary),
    quoteRequestOrdType :: !(Maybe OrdType),
    quoteRequestSpotRatePrecision :: !(Maybe SpotRatePrecision),
    quoteRequestForwardRatePrecision :: !(Maybe ForwardRatePrecision),
    quoteRequestForwardPointsPrecision :: !(Maybe ForwardPointsPrecision),
    quoteRequestInterestRatePrecision :: !(Maybe InterestRatePrecision),
    quoteRequestNearLegRatePrecision :: !(Maybe NearLegRatePrecision),
    quoteRequestFarLegRatePrecision :: !(Maybe FarLegRatePrecision),
    quoteRequestCustomFieldsGroup :: ![CustomFieldsGroupElem]
  }
  deriving stock (Show, Eq, Generic)

instance Validity QuoteRequest

instance IsComponent QuoteRequest where
  toComponentFields ((QuoteRequest {..})) =
    mconcat
      [ requiredFieldB quoteRequestQuoteReqID,
        optionalFieldB quoteRequestRFQReqID,
        optionalFieldB quoteRequestClOrdID,
        optionalFieldB quoteRequestOrderCapacity,
        optionalFieldB quoteRequestUsername,
        requiredGroupB quoteRequestRelatedSymGroup,
        requiredComponentB quoteRequestParties,
        optionalGroupB quoteRequestRegulatoryTradeIDsGroup,
        optionalGroupB quoteRequestOrderAttributesGroup,
        optionalFieldB quoteRequestOptionDate,
        optionalFieldB quoteRequestText,
        optionalFieldB quoteRequestEncodedText,
        optionalFieldB quoteRequestRefSpotDate,
        optionalFieldB quoteRequestProductType,
        optionalFieldB quoteRequestExecutionVenueType,
        optionalFieldB quoteRequestLastCapacity,
        optionalFieldB quoteRequestDayCount,
        optionalFieldB quoteRequestFixingReference,
        optionalFieldB quoteRequestAvgPxPrecision,
        optionalFieldB quoteRequestExpireTime,
        optionalFieldB quoteRequestFiduciary,
        optionalFieldB quoteRequestOrdType,
        optionalFieldB quoteRequestSpotRatePrecision,
        optionalFieldB quoteRequestForwardRatePrecision,
        optionalFieldB quoteRequestForwardPointsPrecision,
        optionalFieldB quoteRequestInterestRatePrecision,
        optionalFieldB quoteRequestNearLegRatePrecision,
        optionalFieldB quoteRequestFarLegRatePrecision,
        optionalGroupB quoteRequestCustomFieldsGroup
      ]
  fromComponentFields = do
    quoteRequestQuoteReqID <- requiredFieldP
    quoteRequestRFQReqID <- optionalFieldP
    quoteRequestClOrdID <- optionalFieldP
    quoteRequestOrderCapacity <- optionalFieldP
    quoteRequestUsername <- optionalFieldP
    quoteRequestRelatedSymGroup <- requiredGroupP
    quoteRequestParties <- requiredComponentP
    quoteRequestRegulatoryTradeIDsGroup <- optionalGroupP
    quoteRequestOrderAttributesGroup <- optionalGroupP
    quoteRequestOptionDate <- optionalFieldP
    quoteRequestText <- optionalFieldP
    quoteRequestEncodedText <- optionalFieldP
    quoteRequestRefSpotDate <- optionalFieldP
    quoteRequestProductType <- optionalFieldP
    quoteRequestExecutionVenueType <- optionalFieldP
    quoteRequestLastCapacity <- optionalFieldP
    quoteRequestDayCount <- optionalFieldP
    quoteRequestFixingReference <- optionalFieldP
    quoteRequestAvgPxPrecision <- optionalFieldP
    quoteRequestExpireTime <- optionalFieldP
    quoteRequestFiduciary <- optionalFieldP
    quoteRequestOrdType <- optionalFieldP
    quoteRequestSpotRatePrecision <- optionalFieldP
    quoteRequestForwardRatePrecision <- optionalFieldP
    quoteRequestForwardPointsPrecision <- optionalFieldP
    quoteRequestInterestRatePrecision <- optionalFieldP
    quoteRequestNearLegRatePrecision <- optionalFieldP
    quoteRequestFarLegRatePrecision <- optionalFieldP
    quoteRequestCustomFieldsGroup <- optionalGroupP
    pure (QuoteRequest {..})

instance IsMessage QuoteRequest where
  messageType Proxy = MsgTypeQuoteRequest

makeQuoteRequest :: QuoteReqID -> (NonEmpty RelatedSymGroupElem -> (Parties -> QuoteRequest))
makeQuoteRequest quoteRequestQuoteReqID quoteRequestRelatedSymGroup quoteRequestParties =
  let quoteRequestRFQReqID = Nothing
      quoteRequestClOrdID = Nothing
      quoteRequestOrderCapacity = Nothing
      quoteRequestUsername = Nothing
      quoteRequestRegulatoryTradeIDsGroup = []
      quoteRequestOrderAttributesGroup = []
      quoteRequestOptionDate = Nothing
      quoteRequestText = Nothing
      quoteRequestEncodedText = Nothing
      quoteRequestRefSpotDate = Nothing
      quoteRequestProductType = Nothing
      quoteRequestExecutionVenueType = Nothing
      quoteRequestLastCapacity = Nothing
      quoteRequestDayCount = Nothing
      quoteRequestFixingReference = Nothing
      quoteRequestAvgPxPrecision = Nothing
      quoteRequestExpireTime = Nothing
      quoteRequestFiduciary = Nothing
      quoteRequestOrdType = Nothing
      quoteRequestSpotRatePrecision = Nothing
      quoteRequestForwardRatePrecision = Nothing
      quoteRequestForwardPointsPrecision = Nothing
      quoteRequestInterestRatePrecision = Nothing
      quoteRequestNearLegRatePrecision = Nothing
      quoteRequestFarLegRatePrecision = Nothing
      quoteRequestCustomFieldsGroup = []
   in (QuoteRequest {..})
