{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Messages.RequestForPositions where

import Data.Validity
import FIX.Fields.Account
import FIX.Fields.AccountType
import FIX.Fields.AcctIDSource
import FIX.Fields.ClearingBusinessDate
import FIX.Fields.Currency
import FIX.Fields.EncodedText
import FIX.Fields.EncodedTextLen
import FIX.Fields.MatchStatus
import FIX.Fields.PosReqID
import FIX.Fields.PosReqType
import FIX.Fields.ResponseDestination
import FIX.Fields.ResponseTransportType
import FIX.Fields.SettlSessID
import FIX.Fields.SettlSessSubID
import FIX.Fields.SubscriptionRequestType
import FIX.Fields.Text
import FIX.Fields.TransactTime
import GHC.Generics (Generic)

-- MessageSpec {messageName = "RequestForPositions", messageType = "AN", messageCategory = "app", messagePieces = [MessagePieceField "PosReqID" True,MessagePieceField "PosReqType" True,MessagePieceField "MatchStatus" False,MessagePieceField "SubscriptionRequestType" False,MessagePieceComponent "Parties" True,MessagePieceField "Account" True,MessagePieceField "AcctIDSource" False,MessagePieceField "AccountType" True,MessagePieceComponent "Instrument" False,MessagePieceField "Currency" False,MessagePieceComponent "InstrmtLegGrp" False,MessagePieceComponent "UndInstrmtGrp" False,MessagePieceField "ClearingBusinessDate" True,MessagePieceField "SettlSessID" False,MessagePieceField "SettlSessSubID" False,MessagePieceComponent "TrdgSesGrp" False,MessagePieceField "TransactTime" True,MessagePieceField "ResponseTransportType" False,MessagePieceField "ResponseDestination" False,MessagePieceField "Text" False,MessagePieceField "EncodedTextLen" False,MessagePieceField "EncodedText" False]}
data RequestForPositions = RequestForPositions
  { requestForPositionsPosReqID :: !PosReqID,
    requestForPositionsPosReqType :: !PosReqType,
    requestForPositionsMatchStatus :: !(Maybe MatchStatus),
    requestForPositionsSubscriptionRequestType :: !(Maybe SubscriptionRequestType),
    requestForPositionsAccount :: !Account,
    requestForPositionsAcctIDSource :: !(Maybe AcctIDSource),
    requestForPositionsAccountType :: !AccountType,
    requestForPositionsCurrency :: !(Maybe Currency),
    requestForPositionsClearingBusinessDate :: !ClearingBusinessDate,
    requestForPositionsSettlSessID :: !(Maybe SettlSessID),
    requestForPositionsSettlSessSubID :: !(Maybe SettlSessSubID),
    requestForPositionsTransactTime :: !TransactTime,
    requestForPositionsResponseTransportType :: !(Maybe ResponseTransportType),
    requestForPositionsResponseDestination :: !(Maybe ResponseDestination),
    requestForPositionsText :: !(Maybe Text),
    requestForPositionsEncodedTextLen :: !(Maybe EncodedTextLen),
    requestForPositionsEncodedText :: !(Maybe EncodedText)
  }
  deriving stock (Show, Eq, Generic)

instance Validity RequestForPositions
