{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Messages.TradeCaptureReportAck where

import Data.Validity
import FIX.Fields.Account
import FIX.Fields.AccountType
import FIX.Fields.AcctIDSource
import FIX.Fields.ClearingFeeIndicator
import FIX.Fields.CustOrderCapacity
import FIX.Fields.EncodedText
import FIX.Fields.EncodedTextLen
import FIX.Fields.ExecID
import FIX.Fields.ExecType
import FIX.Fields.OrderCapacity
import FIX.Fields.OrderRestrictions
import FIX.Fields.PositionEffect
import FIX.Fields.PreallocMethod
import FIX.Fields.ResponseDestination
import FIX.Fields.ResponseTransportType
import FIX.Fields.SecondaryExecID
import FIX.Fields.SecondaryTradeReportID
import FIX.Fields.SecondaryTradeReportRefID
import FIX.Fields.SecondaryTrdType
import FIX.Fields.SubscriptionRequestType
import FIX.Fields.Text
import FIX.Fields.TradeLinkID
import FIX.Fields.TradeReportID
import FIX.Fields.TradeReportRefID
import FIX.Fields.TradeReportRejectReason
import FIX.Fields.TradeReportTransType
import FIX.Fields.TradeReportType
import FIX.Fields.TransactTime
import FIX.Fields.TransferReason
import FIX.Fields.TrdMatchID
import FIX.Fields.TrdRptStatus
import FIX.Fields.TrdSubType
import FIX.Fields.TrdType
import GHC.Generics (Generic)

-- MessageSpec {messageName = "TradeCaptureReportAck", messageType = "AR", messageCategory = "app", messagePieces = [MessagePieceField "TradeReportID" True,MessagePieceField "TradeReportTransType" False,MessagePieceField "TradeReportType" False,MessagePieceField "TrdType" False,MessagePieceField "TrdSubType" False,MessagePieceField "SecondaryTrdType" False,MessagePieceField "TransferReason" False,MessagePieceField "ExecType" True,MessagePieceField "TradeReportRefID" False,MessagePieceField "SecondaryTradeReportRefID" False,MessagePieceField "TrdRptStatus" False,MessagePieceField "TradeReportRejectReason" False,MessagePieceField "SecondaryTradeReportID" False,MessagePieceField "SubscriptionRequestType" False,MessagePieceField "TradeLinkID" False,MessagePieceField "TrdMatchID" False,MessagePieceField "ExecID" False,MessagePieceField "SecondaryExecID" False,MessagePieceComponent "Instrument" True,MessagePieceField "TransactTime" False,MessagePieceComponent "TrdRegTimestamps" False,MessagePieceField "ResponseTransportType" False,MessagePieceField "ResponseDestination" False,MessagePieceField "Text" False,MessagePieceField "EncodedTextLen" False,MessagePieceField "EncodedText" False,MessagePieceComponent "TrdInstrmtLegGrp" False,MessagePieceField "ClearingFeeIndicator" False,MessagePieceField "OrderCapacity" False,MessagePieceField "OrderRestrictions" False,MessagePieceField "CustOrderCapacity" False,MessagePieceField "Account" False,MessagePieceField "AcctIDSource" False,MessagePieceField "AccountType" False,MessagePieceField "PositionEffect" False,MessagePieceField "PreallocMethod" False,MessagePieceComponent "TrdAllocGrp" False]}
data TradeCaptureReportAck = TradeCaptureReportAck
  { tradeCaptureReportAckTradeReportID :: !TradeReportID,
    tradeCaptureReportAckTradeReportTransType :: !(Maybe TradeReportTransType),
    tradeCaptureReportAckTradeReportType :: !(Maybe TradeReportType),
    tradeCaptureReportAckTrdType :: !(Maybe TrdType),
    tradeCaptureReportAckTrdSubType :: !(Maybe TrdSubType),
    tradeCaptureReportAckSecondaryTrdType :: !(Maybe SecondaryTrdType),
    tradeCaptureReportAckTransferReason :: !(Maybe TransferReason),
    tradeCaptureReportAckExecType :: !ExecType,
    tradeCaptureReportAckTradeReportRefID :: !(Maybe TradeReportRefID),
    tradeCaptureReportAckSecondaryTradeReportRefID :: !(Maybe SecondaryTradeReportRefID),
    tradeCaptureReportAckTrdRptStatus :: !(Maybe TrdRptStatus),
    tradeCaptureReportAckTradeReportRejectReason :: !(Maybe TradeReportRejectReason),
    tradeCaptureReportAckSecondaryTradeReportID :: !(Maybe SecondaryTradeReportID),
    tradeCaptureReportAckSubscriptionRequestType :: !(Maybe SubscriptionRequestType),
    tradeCaptureReportAckTradeLinkID :: !(Maybe TradeLinkID),
    tradeCaptureReportAckTrdMatchID :: !(Maybe TrdMatchID),
    tradeCaptureReportAckExecID :: !(Maybe ExecID),
    tradeCaptureReportAckSecondaryExecID :: !(Maybe SecondaryExecID),
    tradeCaptureReportAckTransactTime :: !(Maybe TransactTime),
    tradeCaptureReportAckResponseTransportType :: !(Maybe ResponseTransportType),
    tradeCaptureReportAckResponseDestination :: !(Maybe ResponseDestination),
    tradeCaptureReportAckText :: !(Maybe Text),
    tradeCaptureReportAckEncodedTextLen :: !(Maybe EncodedTextLen),
    tradeCaptureReportAckEncodedText :: !(Maybe EncodedText),
    tradeCaptureReportAckClearingFeeIndicator :: !(Maybe ClearingFeeIndicator),
    tradeCaptureReportAckOrderCapacity :: !(Maybe OrderCapacity),
    tradeCaptureReportAckOrderRestrictions :: !(Maybe OrderRestrictions),
    tradeCaptureReportAckCustOrderCapacity :: !(Maybe CustOrderCapacity),
    tradeCaptureReportAckAccount :: !(Maybe Account),
    tradeCaptureReportAckAcctIDSource :: !(Maybe AcctIDSource),
    tradeCaptureReportAckAccountType :: !(Maybe AccountType),
    tradeCaptureReportAckPositionEffect :: !(Maybe PositionEffect),
    tradeCaptureReportAckPreallocMethod :: !(Maybe PreallocMethod)
  }
  deriving stock (Show, Eq, Generic)

instance Validity TradeCaptureReportAck
