{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.Messages.TradingSessionStatusRequest where

import Data.Validity
import FIX.Fields.SubscriptionRequestType
import FIX.Fields.TradSesMethod
import FIX.Fields.TradSesMode
import FIX.Fields.TradSesReqID
import FIX.Fields.TradingSessionID
import FIX.Fields.TradingSessionSubID
import GHC.Generics (Generic)

-- MessageSpec {messageName = "TradingSessionStatusRequest", messageType = "g", messageCategory = "app", messagePieces = [MessagePieceField "TradSesReqID" True,MessagePieceField "TradingSessionID" False,MessagePieceField "TradingSessionSubID" False,MessagePieceField "TradSesMethod" False,MessagePieceField "TradSesMode" False,MessagePieceField "SubscriptionRequestType" True]}
data TradingSessionStatusRequest = TradingSessionStatusRequest
  { tradingSessionStatusRequestTradSesReqID :: !TradSesReqID,
    tradingSessionStatusRequestTradingSessionID :: !(Maybe TradingSessionID),
    tradingSessionStatusRequestTradingSessionSubID :: !(Maybe TradingSessionSubID),
    tradingSessionStatusRequestTradSesMethod :: !(Maybe TradSesMethod),
    tradingSessionStatusRequestTradSesMode :: !(Maybe TradSesMode),
    tradingSessionStatusRequestSubscriptionRequestType :: !SubscriptionRequestType
  }
  deriving stock (Show, Eq, Generic)

instance Validity TradingSessionStatusRequest
