{-# LANGUAGE TypeApplications #-}
{-# OPTIONS_GHC -Wno-orphans #-}

-- | This module has been GENERATED by fix-codegen.
-- Any manual edits will be undone the next time fix-codegen is run.
module FIX.MessagesSpec where

import FIX.Components.TestUtils
import FIX.Messages.Gen ()
import FIX.Messages.Heartbeat
import FIX.Messages.Logon
import FIX.Messages.QuoteRequest
import FIX.Messages.TestUtils
import Test.Syd
import Test.Syd.Validity

spec :: Spec
spec = do
  describe
    "Heartbeat"
    ( do
        genValidSpec @Heartbeat
        componentSpec @Heartbeat
        messageSpec @Heartbeat "Heartbeat"
    )
  describe
    "Logon"
    ( do
        genValidSpec @Logon
        componentSpec @Logon
        messageSpec @Logon "Logon"
    )
  describe
    "QuoteRequest"
    ( do
        genValidSpec @QuoteRequest
        componentSpec @QuoteRequest
        messageSpec @QuoteRequest "QuoteRequest"
    )
