name: fix-gen
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- test_resources/**/*

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - bytestring
  - fix
  - genvalidity
  - genvalidity-bytestring

tests:
  fix-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - fix
    - fix-gen
    - genvalidity-sydtest
    - sydtest
